# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-06-25 01:48:14.816499 UTC
# Namespace:     dinosaurs.diagnosis

from dinosaurs.diagnosis.GetStatus_1_0 import GetStatus_1_0 as GetStatus_1_0
from dinosaurs.diagnosis.TestInput_1_0 import TestInput_1_0 as TestInput_1_0
from dinosaurs.diagnosis.TestOutput_1_0 import TestOutput_1_0 as TestOutput_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
GetStatus_1 = GetStatus_1_0
TestInput_1 = TestInput_1_0
TestOutput_1 = TestOutput_1_0
