# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zhangge/worknote/ProtocolV4/uavcan/custom_data_types/dinosaurs/diagnosis/TestInput.1.0.uavcan
#
# Generated at:  2025-06-25 01:48:14.820007 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     dinosaurs.diagnosis.TestInput
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class TestInput_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     Class:   None | _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str = None,
                     Channel: None | _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str = None,
                     JSON:    None | _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str = None) -> None:
            """
            dinosaurs.diagnosis.TestInput.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param Class:   saturated uint8[<=16] Class
            :param Channel: saturated uint8[<=16] Channel
            :param JSON:    saturated uint8[<=512] JSON
            """
            self._Class:   _NDArray_[_np_.uint8]
            self._Channel: _NDArray_[_np_.uint8]
            self._JSON:    _NDArray_[_np_.uint8]

            if Class is None:
                self.Class = _np_.array([], _np_.uint8)
            else:
                Class = Class.encode() if isinstance(Class, str) else Class  # Implicit string encoding
                if isinstance(Class, (bytes, bytearray)) and len(Class) <= 16:
                    # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                    # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                    self._Class = _np_.frombuffer(Class, _np_.uint8)  # type: ignore
                elif isinstance(Class, _np_.ndarray) and Class.dtype == _np_.uint8 and Class.ndim == 1 and Class.size <= 16:  # type: ignore
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._Class = Class
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    Class = _np_.array(Class, _np_.uint8).flatten()
                    if not Class.size <= 16:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'Class: invalid array length: not {Class.size} <= 16')
                    self._Class = Class
                assert isinstance(self._Class, _np_.ndarray)
                assert self._Class.dtype == _np_.uint8  # type: ignore
                assert self._Class.ndim == 1
                assert len(self._Class) <= 16

            if Channel is None:
                self.Channel = _np_.array([], _np_.uint8)
            else:
                Channel = Channel.encode() if isinstance(Channel, str) else Channel  # Implicit string encoding
                if isinstance(Channel, (bytes, bytearray)) and len(Channel) <= 16:
                    # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                    # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                    self._Channel = _np_.frombuffer(Channel, _np_.uint8)  # type: ignore
                elif isinstance(Channel, _np_.ndarray) and Channel.dtype == _np_.uint8 and Channel.ndim == 1 and Channel.size <= 16:  # type: ignore
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._Channel = Channel
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    Channel = _np_.array(Channel, _np_.uint8).flatten()
                    if not Channel.size <= 16:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'Channel: invalid array length: not {Channel.size} <= 16')
                    self._Channel = Channel
                assert isinstance(self._Channel, _np_.ndarray)
                assert self._Channel.dtype == _np_.uint8  # type: ignore
                assert self._Channel.ndim == 1
                assert len(self._Channel) <= 16

            if JSON is None:
                self.JSON = _np_.array([], _np_.uint8)
            else:
                JSON = JSON.encode() if isinstance(JSON, str) else JSON  # Implicit string encoding
                if isinstance(JSON, (bytes, bytearray)) and len(JSON) <= 512:
                    # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                    # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                    self._JSON = _np_.frombuffer(JSON, _np_.uint8)  # type: ignore
                elif isinstance(JSON, _np_.ndarray) and JSON.dtype == _np_.uint8 and JSON.ndim == 1 and JSON.size <= 512:  # type: ignore
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._JSON = JSON
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    JSON = _np_.array(JSON, _np_.uint8).flatten()
                    if not JSON.size <= 512:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'JSON: invalid array length: not {JSON.size} <= 512')
                    self._JSON = JSON
                assert isinstance(self._JSON, _np_.ndarray)
                assert self._JSON.dtype == _np_.uint8  # type: ignore
                assert self._JSON.ndim == 1
                assert len(self._JSON) <= 512

        @property
        def Class(self) -> _NDArray_[_np_.uint8]:
            """
            saturated uint8[<=16] Class
            DSDL does not support strings natively yet. To interpret this array as a string,
            use tobytes() to convert the NumPy array to bytes, and then decode() to convert bytes to string:
            .Class.tobytes().decode()
            When assigning a string to this property, no manual conversion is necessary (it will happen automatically).
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._Class

        @Class.setter
        def Class(self, x: _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str) -> None:
            x = x.encode() if isinstance(x, str) else x  # Implicit string encoding
            if isinstance(x, (bytes, bytearray)) and len(x) <= 16:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._Class = _np_.frombuffer(x, _np_.uint8)  # type: ignore
            elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size <= 16:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._Class = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.uint8).flatten()
                if not x.size <= 16:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'Class: invalid array length: not {x.size} <= 16')
                self._Class = x
            assert isinstance(self._Class, _np_.ndarray)
            assert self._Class.dtype == _np_.uint8  # type: ignore
            assert self._Class.ndim == 1
            assert len(self._Class) <= 16

        @property
        def Channel(self) -> _NDArray_[_np_.uint8]:
            """
            saturated uint8[<=16] Channel
            DSDL does not support strings natively yet. To interpret this array as a string,
            use tobytes() to convert the NumPy array to bytes, and then decode() to convert bytes to string:
            .Channel.tobytes().decode()
            When assigning a string to this property, no manual conversion is necessary (it will happen automatically).
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._Channel

        @Channel.setter
        def Channel(self, x: _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str) -> None:
            x = x.encode() if isinstance(x, str) else x  # Implicit string encoding
            if isinstance(x, (bytes, bytearray)) and len(x) <= 16:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._Channel = _np_.frombuffer(x, _np_.uint8)  # type: ignore
            elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size <= 16:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._Channel = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.uint8).flatten()
                if not x.size <= 16:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'Channel: invalid array length: not {x.size} <= 16')
                self._Channel = x
            assert isinstance(self._Channel, _np_.ndarray)
            assert self._Channel.dtype == _np_.uint8  # type: ignore
            assert self._Channel.ndim == 1
            assert len(self._Channel) <= 16

        @property
        def JSON(self) -> _NDArray_[_np_.uint8]:
            """
            saturated uint8[<=512] JSON
            DSDL does not support strings natively yet. To interpret this array as a string,
            use tobytes() to convert the NumPy array to bytes, and then decode() to convert bytes to string:
            .JSON.tobytes().decode()
            When assigning a string to this property, no manual conversion is necessary (it will happen automatically).
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._JSON

        @JSON.setter
        def JSON(self, x: _NDArray_[_np_.uint8] | list[int] | memoryview | bytes | bytearray | str) -> None:
            x = x.encode() if isinstance(x, str) else x  # Implicit string encoding
            if isinstance(x, (bytes, bytearray)) and len(x) <= 512:
                # Fast zero-copy initialization from buffer. Necessary when dealing with images, point clouds, etc.
                # Mutability will be inherited; e.g., bytes - immutable, bytearray - mutable.
                self._JSON = _np_.frombuffer(x, _np_.uint8)  # type: ignore
            elif isinstance(x, _np_.ndarray) and x.dtype == _np_.uint8 and x.ndim == 1 and x.size <= 512:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._JSON = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.uint8).flatten()
                if not x.size <= 512:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'JSON: invalid array length: not {x.size} <= 512')
                self._JSON = x
            assert isinstance(self._JSON, _np_.ndarray)
            assert self._JSON.dtype == _np_.uint8  # type: ignore
            assert self._JSON.ndim == 1
            assert len(self._JSON) <= 512

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
            assert len(self.Class) <= 16, 'self.Class: saturated uint8[<=16]'
            _ser_.add_aligned_u8(len(self.Class))
            _ser_.add_aligned_array_of_standard_bit_length_primitives(self.Class)
            # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
            assert len(self.Channel) <= 16, 'self.Channel: saturated uint8[<=16]'
            _ser_.add_aligned_u8(len(self.Channel))
            _ser_.add_aligned_array_of_standard_bit_length_primitives(self.Channel)
            # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
            assert len(self.JSON) <= 512, 'self.JSON: saturated uint8[<=512]'
            _ser_.add_aligned_u16(len(self.JSON))
            _ser_.add_aligned_array_of_standard_bit_length_primitives(self.JSON)
            _ser_.pad_to_alignment(8)
            assert 32 <= (_ser_.current_bit_length - _base_offset_) <= 4384, \
                'Bad serialization of dinosaurs.diagnosis.TestInput.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> TestInput_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "Class"
            # Length field byte-aligned: True; all elements byte-aligned: True.
            _len0_ = _des_.fetch_aligned_u8()
            assert _len0_ >= 0
            if _len0_ > 16:
                raise _des_.FormatError(f'Variable array length prefix {_len0_} > 16')
            _f0_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, _len0_)
            assert len(_f0_) <= 16, 'saturated uint8[<=16]'
            # Temporary _f1_ holds the value of "Channel"
            # Length field byte-aligned: True; all elements byte-aligned: True.
            _len1_ = _des_.fetch_aligned_u8()
            assert _len1_ >= 0
            if _len1_ > 16:
                raise _des_.FormatError(f'Variable array length prefix {_len1_} > 16')
            _f1_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, _len1_)
            assert len(_f1_) <= 16, 'saturated uint8[<=16]'
            # Temporary _f2_ holds the value of "JSON"
            # Length field byte-aligned: True; all elements byte-aligned: True.
            _len2_ = _des_.fetch_aligned_u16()
            assert _len2_ >= 0
            if _len2_ > 512:
                raise _des_.FormatError(f'Variable array length prefix {_len2_} > 512')
            _f2_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.uint8, _len2_)
            assert len(_f2_) <= 512, 'saturated uint8[<=512]'
            self = TestInput_1_0.Request(
                Class=_f0_,
                Channel=_f1_,
                JSON=_f2_)
            _des_.pad_to_alignment(8)
            assert 32 <= (_des_.consumed_bit_length - _base_offset_) <= 4384, \
                'Bad deserialization of dinosaurs.diagnosis.TestInput.Request.1.0'
            assert isinstance(self, TestInput_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'Class=%s' % repr(bytes(self.Class))[1:],
                'Channel=%s' % repr(bytes(self.Channel))[1:],
                'JSON=%s' % repr(bytes(self.JSON))[1:],
            ])
            return f'dinosaurs.diagnosis.TestInput.Request.1.0({_o_0_})'

        _EXTENT_BYTES_ = 548

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8UR7IY0{@*=ZEqYk5Wa(?cWEhH2sGkF>IrBYM0G8%LP$u!Nr<u}Ig&OKeUateot&-i+KcVI<_bvZ2dW@hqEgH!KJpHKqJM(_'
            '!+3X-yIk+6+WoTj%y>NW%=nqzxu0$|YsF_zXTw;>Nrz}qoF@D>4HM{)NT!+8+<>zuH;u|8lPkD9%)srt*YCLR+=`tif~KfH6LTRo'
            '&6V!Noc3|eb>}i@b4g^m>1@E)Ic}V7k^v~qrEsif8(Y<S-v#xccGul;_5`8EC?4hpw7Y>f%!uvK%Gvo(IVABYrsE{0h7#igwJ*&$'
            't`r?QySznFijprt^bPyiOOGaal0X6}2vhl+5l*If$_*c&#nKg_d0#+$Nf_vZI_mEP3ArIjah(gA7;HqfA*qbPu@~*B-hm^3tkXr^'
            's#hUGweQ`Av(FK2sEDbG#~tnEp<O^v8I8CZx}asBtyE;&gHs02UM_=Rr-LSIvsZ$;cgfE9({m(Dw6kXq(i=I)OwHup*{43?rUY#h'
            'w^e%fNg^|6+q0bLVH(PWM+nj?q!Ph1SpM}46g5(fKsrVu#<8UAZToyziijEzQ%!x+-co_^&4TvNtmR2U)$jq!V`M;+9Ndp?C1~E$'
            'A$zw1<9$4}yg@}DHXsATXN7c=q;v<N#RDG|Le@R-Rp6I$fkpBQZ?<b2zNmRZ{qdmgO>6gpX8F&t?y!?lQMCVB9s&lmj#cRed+f_;'
            '2iO&~@;9-0JKs&H#$wHpSR$4+htgJ+%@R9RtzMWY_iII=*;&ls+=S|lQgxnPC=+{Y44e;2(T5)1$-KwRKC4#241h4Z8fLfqKiNGJ'
            '28}MGLO|l!Rd(%>@?WhzaRh+YV*=2c0f6^E8-dkY>!A>|(5%&ZI0kc{Z?3OZ0DxT@V@?tdOJepBeZ>~pH|#q5nSGlh|HP0f@J}js'
            'KiH>{A9f%nnN)`G*sa+`qGhfkKt%#1qsT6{;eQDa@xAqs*>`$gx{t4-egV6XNk0J^x3M7oKCYU#q`E1jr{?25C5?<^vh@zWz?=>u'
            'Dx6)6a&2TfqG{~qg~I_-tg8`%d^Z{*Z+0$rDi_96;Sym~V}#1HGt%*ZN8t9@Rr_jI-P+DIw2f>>QW%BX?Z~uI7lD60tpcHP$O&{&'
            'j+<F=EF8vxsUD0ou*(HP#7Lr~G=)cvB#d19%L@CI{l<Q0f3QE<U+i!8j}Ll!iy>|GXpA@aA0QsoPH)AL^!{U5zK4@IE3d@an;&_2'
            'MT@cRv0ki?#Q#>-lk&Tzc^k#;#c}gyK1J>uxbq);k8JXS2mk;'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     status: None | int | _np_.int16 = None) -> None:
            """
            dinosaurs.diagnosis.TestInput.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param status: saturated int16 status
            """
            self._status: int

            self.status = status if status is not None else 0  # type: ignore

        @property
        def status(self) -> int:
            """
            saturated int16 status
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._status

        @status.setter
        def status(self, x: int | _np_.int16) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if -32768 <= x <= 32767:
                self._status = x
            else:
                raise ValueError(f'status: value {x} is not in [-32768, 32767]')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_i16(max(min(self.status, 32767), -32768))
            _ser_.pad_to_alignment(8)
            assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 16, \
                'Bad serialization of dinosaurs.diagnosis.TestInput.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> TestInput_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f3_ holds the value of "status"
            _f3_ = _des_.fetch_aligned_i16()
            self = TestInput_1_0.Response(
                status=_f3_)
            _des_.pad_to_alignment(8)
            assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 16, \
                'Bad deserialization of dinosaurs.diagnosis.TestInput.Response.1.0'
            assert isinstance(self, TestInput_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'status=%s' % self.status,
            ])
            return f'dinosaurs.diagnosis.TestInput.Response.1.0({_o_0_})'

        _EXTENT_BYTES_ = 2

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8UR7IY0{?YWT~8B16fLn(D1Ja7`e=P2RdM-<Pd;j5LMpWZ!kd}Q?p!+)c4s#8QCbobdC*`oi6)Hy*E`$NBBuMYclO>nd(OS*'
            'eyjgEsn@E<KQBkjusk6Kw4k}TplJ>X$y8A)BP;~}=-6tPS*PJ-R6@83FR#L7X!}JXX@U7ICZsadX_GKP`xpz8oPe<hvUD~%0#hn!'
            'uyC0SKpUZC;5FYkoy0exv(Tyi2v@<c5^Aj$sk30hmoSgpv?%z+j{<Tw<J2UKT1sprI`4X^MIo#hV8!~e=u2P+(n25fzw%Z|DlExC'
            '_AL*cHH6Nnv7}H80^jscd$%z0TJiyNhcSh6YTv_A@SDU~DjC)6F3`10`J!LKlyxTfI$<gcz7||c{l*>nBpr?0dl`6(uN$Pppwy62'
            '3oQKfkI7dt1V&1wEfFkq{W>wq=?pND11Tx~%s1jI7isV-Jsiuh7r)-1xP=}3H&=0djSEg?zaQswuJoByv9HaZR#s&yKYbhglB0u+'
            'N^Do=j8(;~$EaXsI{hl1%pc{?9I%({CKCu7JF`JJHONqdv~e~AkwLiTFZ{Nic%?b+&%4%cOPy`El;xn$g@Kj<Xo1#JC8%z#>d@G#'
            '60xFZ+H(o5ObMaVsVTuft9nJOB3db1L7I{xBmSz*U-NDLh9`W7@A5sqU(v6VG)KIxTX)T-i(>5kbMOz}3;U@$ALDW2FaLn3GWga!'
            '5Hl)Ll?(L7#vv36y=!q<K9``WReI*qC6aN08^90zlOAQLz5ibk@5XG`<vG=(`&mR7(A+`z722J(-zLR1EyqBiv+PooTL>8!00TOV'
            'K_f1K%W1sbBrq(gtTwspQj@wg`3p;$AWB~Z000'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    def __repr__(self) -> str:
        return 'dinosaurs.diagnosis.TestInput.1.0()'


    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8UR7IY0{@*>-ESL35O-)2J5F01LK~#2#0Xkah)gO~0u>=dBM`+TwURUsNM%{yZ9UtZZ;#!*G_Hh{Jb)6h5|y&Ng8+%|F9~?!'
        'k$-|W9(dxPVD|3(5hrev`r*7cJ3Bk`o0;F-=J2QI$8*WgOh+wW`9Xy!COHlGJz5V~g?OSF3B@(DW_+2+b?&j1R>bVCy|iUNuruZq'
        'k?j4LDNVGKL(ZI9)-v{VEc-M^NJyJ#=Yr2ep=c~s#pkqvYpyCQXyJMo#k#VTnzN=r)|pgXgwAMwHCyl6>QFWJk=;Uv2-RBhdaRkU'
        'xA2AmF?6)78F_=V!0-B0BtF$Nb={mBa9m2-vSw<Pq7)@>v#_DzH7D(df(5L}!VHQ*?nII|x#sJrF?lmoyb&`0dZ<~0$-VZ*Nu6sF'
        'B-hz$0iE?I;@lKI;yi86*4l>LvC2H|Ex0X2DEFaVvgUE3G!1<!{a!=caovoerHFc5w`{d!9?Q1KZ3j-4$EQ*!;F)RxF2J+ZA!ibv'
        'bEk(%Jy6zMY=_r1j*;sAcWX{w<2nUx8DF#T%n2eQYs!O+s8+Ks0`4J53#=&+JdNqU5iv=%kX?{Qi3c203NM*6^CI-9X5oRVE@-DI'
        'S?G!d^&ee~gMiA`KFv|GPJ@`)PwY&!a9`EoY6iwDcxq~ih7GpFBBuEum)1y=ZXmRH;PpfZZ?<hE_%(TmNpcIPwrTP%sc}Hv@#>IM'
        '&E2mS(*GFq&Nd<%Cgr~v*BLsrf?2s)-G<eJ4!}F8<!*wa8JQ2L!ek8-Um%t_i_$Y$G*7^}Z1rScx-TV(hUYPY*}kp0bn7x)NdtSa'
        '2b@<^(KQEef80H43)!kR03eJmhtX|5Ai85=ke>${hAgl^;JstTzmR)m4*;cy1fVnk0B3(N0t>m)p%9c%tyDT3gW<Q9Z!Bg2Ff-Z1'
        'oTT1LiP?GdE}Vr;pzs-N#mGNCizIU`<=Y)|8u?*^`6Loj6YkqZGeMMyrN?k1U?if*E++5(0$#^{t0A**)SPq|yJF}CtU?fO0_5*u'
        'LK+QR748bT779nr#hMgacp_N6f*lysb&rPDOn9-<qS>WstmU!J07=%_2tmH<4w1{1xk_e2J1U$cKoxo@9XqRZj@fM>=IJQAwHzx}'
        ')}ri*P)mHh?ddY^dCYZBDM2V5h9R0r$IT!=#yWmrsO@pa%v6F9(Sk@JbYf8<2_x5jJp<psx9}Z&4?n<<@Du#(oIbe3khW^n$D14b'
        'hzEBMF2%0&uZPfl87Fa+UWv0e-qUzViNRV=Ee>_Xe`nhL@{d#XGK$L+z3PSd0C_^0r|~O8A@+)8<0+rHS2Pz7`<zJ6SvUzLn7Czo'
        '+JD+iEDs#NS-WRcP&A`BOm(cX9-{C$`u89FtKf?r_;L}xIv|Vi3;dd7@;6s%v+WRysimvsxw2TBEej1y-sM<+im@`2G87fC@W)Y0'
        'tk4OO!Jo&frEZS*kySexn7e9ePc9IO^ACi)gY--f)CI@G*_Yye9{vY+3$l}`l%*WPGj~RYa=AMv+@s(gqxguA1o;k{`TfW!4u&qS'
        'SN;dBmX^vW3jhE'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
