# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zhangge/worknote/ProtocolV4/uavcan/custom_data_types/dinosaurs/actuator/wheel_motor/PidParameter.1.0.uavcan
#
# Generated at:  2025-06-25 01:48:14.942377 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     dinosaurs.actuator.wheel_motor.PidParameter
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class PidParameter_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     pid_params: None | _NDArray_[_np_.float32] | list[float] = None,
                     reserved:   None | _NDArray_[_np_.float32] | list[float] = None) -> None:
            """
            dinosaurs.actuator.wheel_motor.PidParameter.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param pid_params: saturated float32[4] pid_params
            :param reserved:   saturated float32[12] reserved
            """
            self._pid_params: _NDArray_[_np_.float32]
            self._reserved:   _NDArray_[_np_.float32]

            if pid_params is None:
                self.pid_params = _np_.zeros(4, _np_.float32)
            else:
                if isinstance(pid_params, _np_.ndarray) and pid_params.dtype == _np_.float32 and pid_params.ndim == 1 and pid_params.size == 4:  # type: ignore
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._pid_params = pid_params
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    pid_params = _np_.array(pid_params, _np_.float32).flatten()
                    if not pid_params.size == 4:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'pid_params: invalid array length: not {pid_params.size} == 4')
                    self._pid_params = pid_params
                assert isinstance(self._pid_params, _np_.ndarray)
                assert self._pid_params.dtype == _np_.float32  # type: ignore
                assert self._pid_params.ndim == 1
                assert len(self._pid_params) == 4

            if reserved is None:
                self.reserved = _np_.zeros(12, _np_.float32)
            else:
                if isinstance(reserved, _np_.ndarray) and reserved.dtype == _np_.float32 and reserved.ndim == 1 and reserved.size == 12:  # type: ignore
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._reserved = reserved
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    reserved = _np_.array(reserved, _np_.float32).flatten()
                    if not reserved.size == 12:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'reserved: invalid array length: not {reserved.size} == 12')
                    self._reserved = reserved
                assert isinstance(self._reserved, _np_.ndarray)
                assert self._reserved.dtype == _np_.float32  # type: ignore
                assert self._reserved.ndim == 1
                assert len(self._reserved) == 12

        @property
        def pid_params(self) -> _NDArray_[_np_.float32]:
            """
            saturated float32[4] pid_params
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._pid_params

        @pid_params.setter
        def pid_params(self, x: _NDArray_[_np_.float32] | list[float]) -> None:
            if isinstance(x, _np_.ndarray) and x.dtype == _np_.float32 and x.ndim == 1 and x.size == 4:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._pid_params = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.float32).flatten()
                if not x.size == 4:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'pid_params: invalid array length: not {x.size} == 4')
                self._pid_params = x
            assert isinstance(self._pid_params, _np_.ndarray)
            assert self._pid_params.dtype == _np_.float32  # type: ignore
            assert self._pid_params.ndim == 1
            assert len(self._pid_params) == 4

        @property
        def reserved(self) -> _NDArray_[_np_.float32]:
            """
            saturated float32[12] reserved
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._reserved

        @reserved.setter
        def reserved(self, x: _NDArray_[_np_.float32] | list[float]) -> None:
            if isinstance(x, _np_.ndarray) and x.dtype == _np_.float32 and x.ndim == 1 and x.size == 12:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._reserved = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.float32).flatten()
                if not x.size == 12:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'reserved: invalid array length: not {x.size} == 12')
                self._reserved = x
            assert isinstance(self._reserved, _np_.ndarray)
            assert self._reserved.dtype == _np_.float32  # type: ignore
            assert self._reserved.ndim == 1
            assert len(self._reserved) == 12

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            assert len(self.pid_params) == 4, 'self.pid_params: saturated float32[4]'
            _ser_.add_aligned_array_of_standard_bit_length_primitives(self.pid_params)
            assert len(self.reserved) == 12, 'self.reserved: saturated float32[12]'
            _ser_.add_aligned_array_of_standard_bit_length_primitives(self.reserved)
            _ser_.pad_to_alignment(8)
            assert 512 <= (_ser_.current_bit_length - _base_offset_) <= 512, \
                'Bad serialization of dinosaurs.actuator.wheel_motor.PidParameter.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> PidParameter_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "pid_params"
            _f0_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.float32, 4)
            assert len(_f0_) == 4, 'saturated float32[4]'
            # Temporary _f1_ holds the value of "reserved"
            _f1_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.float32, 12)
            assert len(_f1_) == 12, 'saturated float32[12]'
            self = PidParameter_1_0.Request(
                pid_params=_f0_,
                reserved=_f1_)
            _des_.pad_to_alignment(8)
            assert 512 <= (_des_.consumed_bit_length - _base_offset_) <= 512, \
                'Bad deserialization of dinosaurs.actuator.wheel_motor.PidParameter.Request.1.0'
            assert isinstance(self, PidParameter_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'pid_params=%s' % _np_.array2string(self.pid_params, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
                'reserved=%s' % _np_.array2string(self.reserved, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
            ])
            return f'dinosaurs.actuator.wheel_motor.PidParameter.Request.1.0({_o_0_})'

        _EXTENT_BYTES_ = 256

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8UR7IY0{^9!+ix316o>89u^q=rlji0&ZQ_QsP154#;-pR~gwiTfHBGQm=nJY=Ywt9($$Ho9B~2<Jr3g?fZIy*iA9z3r9ucY#'
            'PZbjVUy#xZ2#~m6B{;`EX)a9=h)B+Fc4zj?nKR$aIm?mTUnE17Kfk-Yq&b?AQ5<gTs-a(13kJ_9MXOY{9Np#8Z#c^hy#!6|rKK{L'
            'w`Bh{`I_wWql#{t+?FEbH(YRSujqO<-#nyNG1U^77}0doa#YWDGAayHUCYi~5u6)J$-;JC*Yc_jLtSoXX85ZfcU<Yml?84)x@F=N'
            'v5VBcC0Uq--jdg(U$3aHYwHEi<&L}r^X;&h$D^cQJE?O+TlX-bXsW9!F1qb^?(n&7t4q>vozxe(cAlHFt~iaaHm|io;RY{p(<Ng&'
            '_)@kpmihvWsGBq_)!l5RUMc9VVpJxPEDin@RmX)eX<UkKzdgV9IewNo1ASB21wjeDDQCb*#c@?rQ*CXdq3d9$q|TbU>uEUgWgE5u'
            'g6TkzC#elK{39dT!QtHSNOo*&BsV&o%Z-lbhK5cIW`}Yk*<5yXXl#6VG@BiiIG0!O>%hCRTGZVo$s&G4DHve!@Y=%H9e^0PTc4$$'
            'd_i}s;k*Ek6as&jVwI(z-pPowR4Q18UX*^z6fap2R&@TwGPjYcjdT`;4m&MQ`g>-0nY;S-<7$+7@Lf#6xZTs9VW{@f)<IxvK{Y%s'
            'S7aYc2TlQ29#KlVDcLeM)J1H>aFaYkMXM}~Lqh?pA>D;q6R-$9*P`wUSd`w!NaNIBN6!h=c);pWV*yLja|3F9z#3`XZhGHD-#4Sy'
            '1#A!Xx1cr#td+*K(ffAPJpt=LZ3tM3`uCE5`%qH>>qKo0*nZTefE_?h2CR$5ccVrEmZtd+q8<oX59+>vJ%!p4uwJrr2(>w2hsm!a'
            'w4Oe)*N<8oumSS(DC$7Kj-mDi>}k})0n4EF2JAR$PrwGNTf~M?y8<?hx<6ne<VTj)Gm6?Curc!I1jQjo>l-J(PSQG`K}`hg6#4fo'
            'YBXTa(Yhzd&*!V__u#zo#j<KvZY+Ga9C!r;M<o12S=W>@UUzU<B8p}K%X?Svz4zeb4_5Df_R4(uSbAQEUlD%VB{*iHt;(uMiB4*D'
            'iG$SYWodCp^oxP(;;6{{*Apy;SyGIMv5GM<E>4lv32~ZQXJNpEn5+&sw|)Wyn_3Qw^Z0LSN8&?Uh>sBQAtFAyh4?5DA0grsM0|*d'
            'j}h@vBED`5@d+Y6O2kKq_y`dnCE^oAd=n8LBI4_a_*No5O2oGk@i8JkMZ_n!5Z^|`Cy4kSB0fdLHxls?BK{x|pCaOS6Y)_ZzK@7c'
            '6Y(h`zKMvB6Y(J;zMqKiA>uoU_*NpmfryV1@nb~%AQ3-6#P<^MT||6}h~GoRCyDszI`Lu!8bHH3=W&}u>RaG&2fyRDe)-`W4{yIa'
            'G`xEEqx&nbKe+wL>gP8BK<>9}Na9Lisai20d2fq$@kmGya-zn|HZQ7Bg2)?wqjDJ&u~N2dSJ5>&?Kdlq<=I6J9R`P^1sTtep%{7r'
            'vRxhunZ-Q5y#*J3_&A(8VPRPkyDC(3b{1OkE0#TPT38_@@;1~YMa#IDg`3|~7mBJW{pO<QxK?SsT7a`#_qeJ718a2+R3#fK8|im!'
            's%?fcgBddEV!CcogzDgBfOP{#OD}SH9pcsY@Y8z_?=0ufovlXe{>_y~ckW2PsS=-Rd1k^#)w<_jd6L}d2`qlC&f<PYC1#3iDYj*~'
            'l^GmJ>riog*C)OgKZqa2PvU3si}+RihHh_vV?YAUs~UJR`$U$7-i_nh&R8byrnznI#;O8SH^c-NxBlf^Q#cfQZ01?056jj0pd!Qz'
            'i7kus@Pq3}tW3j;_ql`DRHz27DfqYcey$tLu(-EfUlm<ZFOs53G~?{;LUQrdMjpl2H^ev7;@fS4BYqcuh(9YK`U`e(E(9~ph2h`-'
            '-=w)XnAu@Jp!VR45KdQ4h2nlY9G7arZYzST8c3xgh4QiGWynagCfClHE}!N0rrMKI$q^RD+yDs$Lb2UO&$X{@!`$BL(w;~Un|8Zn'
            '1`Zkjry4A(%vY+YsZe-Ju8C8wnZ|93<2J1&45zYRl^w>;^fsONY36V4%7XLk3;+N'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        SET_SUCCESS:          int = 0
        PARAMETERS_EXCEPTION: int = 1

        def __init__(self,
                     status: None | int | _np_.int32 = None) -> None:
            """
            dinosaurs.actuator.wheel_motor.PidParameter.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param status: saturated int32 status
            """
            self._status: int

            self.status = status if status is not None else 0  # type: ignore

        @property
        def status(self) -> int:
            """
            saturated int32 status
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._status

        @status.setter
        def status(self, x: int | _np_.int32) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if -2147483648 <= x <= 2147483647:
                self._status = x
            else:
                raise ValueError(f'status: value {x} is not in [-2147483648, 2147483647]')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_i32(max(min(self.status, 2147483647), -2147483648))
            _ser_.pad_to_alignment(8)
            assert 32 <= (_ser_.current_bit_length - _base_offset_) <= 32, \
                'Bad serialization of dinosaurs.actuator.wheel_motor.PidParameter.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> PidParameter_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f2_ holds the value of "status"
            _f2_ = _des_.fetch_aligned_i32()
            self = PidParameter_1_0.Response(
                status=_f2_)
            _des_.pad_to_alignment(8)
            assert 32 <= (_des_.consumed_bit_length - _base_offset_) <= 32, \
                'Bad deserialization of dinosaurs.actuator.wheel_motor.PidParameter.Response.1.0'
            assert isinstance(self, PidParameter_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'status=%s' % self.status,
            ])
            return f'dinosaurs.actuator.wheel_motor.PidParameter.Response.1.0({_o_0_})'

        _EXTENT_BYTES_ = 4

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8UR7IY0{@LvS!)zQ5Z+*pP2v?23<{c6RFZ(>f%xECTs9gv*$lfe_##cuOlPaHcY5gV*<=HPc~BxWD5U+rR?i+eB<Q?MO;>f*'
            'S5@CPU&nuMPn3$sE@iz$Cn6x4DNY4Hq>*3&iDf5~nj7ZqwU$wNY;whRdKq&kZso{*am#jsq_l(nmkCd$rn%Aq#V~553ig39K|0dg'
            'Ax}c8Fw`&=G?~t1s_|NxbeYmzrVdJWYIk6txcXSV^xYjfJ4>iBibuI&+I_-;mp~mwIXkh=nMh6{&X9x}N{q*S+4W5E4mZ4u5pylx'
            'PFb>%8rEj&e7CbC;)V#8whg#?1yjdV8*DLQ4i@aKaG1tl3##bb@-FPB^vyM$T_D=fG@&Xvo9H-?V8TwK%jDYGagxZ`*^<NK>$Y6Q'
            'N#P|kLILw|Yhc~3SKtoZgQb3o*;Z|bv_4d;wN}f)eRyCeNtcQoySh8<n;m3|X+P$3U6-5G;29OeGO%i=_Z03DPZ3mkePE;Cjy-d}'
            '9UWoShyMb#5Uw@XwrV@IW{cE5R%_wT#&)AX2dnU8PzzqzvFD?t%+8-#JBfOIlKJEnn1dB~1h3&$j_XJmb`w*>68FPiCwu&WB_xx|'
            '5T3Y(og-T2DrV>qjARstZKwQ8@W|Qe5XpTI`qL9!?$}eDJxI^ysY9S?yY1()FV*K%dS1<h3aK1RvHQ~5$((j$nj&4|TpQUr<rofY'
            'dL#x+Fq8vw`HUc(T|6g==fSgJkkWXj%oCs*5i6D&&($uEnL93adb5~DUz{nr`?~nAnpe-(^h+NKk=ey!Jj6(%q%=hdolz_bZ<pa6'
            'Y`}Y{!zOG&1GWo<<0KMT>+z6Sr-Vkl=HfTje#6aX@!eu0GTSReX3kbFOQL(7ND7W}nBQU@iE{NE+|HOP+8YUTlElDK^w739LYm+#'
            '+J6Os@ZLr)1XaC@UReF<mg|*YI>LWa*3aPT<vhYZJ3RGbM}r=CW6BFY7u4gQ@q(gh@!M+Tk!Nr42SU`fVOj+M00'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    def __repr__(self) -> str:
        return 'dinosaurs.actuator.wheel_motor.PidParameter.1.0()'


    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8UR7IY0{^X->u(#!5x|c&MN-t;dd7+z#!(&FacMm$nQq#ojvj!q6+?@5(4q}4N8Uzz)bWnJhav?ipcHLk0~`1PpHuilKeXtl'
        'qA-en3JNrTN<TSq`=Kb>0)4+`cteq5D7Q{ZfIG|Ez1i8B-|h?#;`e?vtTaCInfku&>Sk7TxnpRi@wQerc~-61wYu#Z9uH+-i95SS'
        'h2Pk(^YCtX{+;k!;hY>$9sW(9yPoRdbD_wAHEtR;ctt-tGoc!m#hu2KlIQpp&v!bM^{AFsgQb>q!?In?cigN7(=^X^vTq5_O|@oY'
        'zi8-1&4H;Ncd}d2`k_pzyWDXN+rlN1uTlSQ$YM<SUic2|K-E0YG0MKj-SBl-@0d*=&I)DEhQUp}Wno&?HBXE7DyNTm-Ep-2P>yXF'
        'dtCntx3)cT6(4mvj+?y3Epps(w$vT;rLhY$dN)j4^NwoiQ_F^@nvF$5mI3=J8pNVz>kx}sIZ<rBj<01`VQdqJz$wai!!0mUbv@0}'
        'HAin(bPM#<v~A1qd>t2l(}6I6GhJ}<2K7OQe10i6znEWK%B`#{<(C)p`Q<D5g@w!WxrO{vE}vUoSh=#eoXgFJxRzg*y<lBks~FyX'
        '$l@}tmQB!juDS7+0pJ6#^LHrwUopJMohA55E|4cxyB^BSaZ23%TG=*@N+?G+dCdm5qVccRxr0=-(^(M)L|VKoPi^r!_l)lIPN+Lz'
        'yI6yHLj~V7HD|wb66o61OrM8$!a0@++%oJuuGS1IWCz&M_OO%0Ao-?-T3HOIDgiq|@+8U=0gKb`9+W2omZ0ZJk|`SRrQd0ksetvN'
        'Oa`o<eh;AR3)mpd8=~jK^!^CS-hiE=@llk60UM)v<Mez2<*9&8q8td=6pcSc_MJvK6|iZPV*z^_<#51eQ1%Dx49$NAWjtURTK`#;'
        'GXXn`@^rwSLpd3+S<>@4lp_H<M|M3=`<Wws=TY_q>;l>O0?G>kyNGfwV4p{ME?`-dvjMw=@@&B7qY$wLlxG6Ai1O)xEs-5L+Rrk|'
        'iGZz;J(tN3dD`C<vg-@9&lgdq1NKF-?@K5X0egw|{W974<!JvtoHxE#*Q~~kh0hKGzl`9BA(^flx?0EU4h~CP)ooz;sfQo_;NzeE'
        '@Zkr)`1(%$VrIvHZw0>k>u}7(>4;S^BQn%`PMo9Od6p3uL{?n7CFaG_lb&F4ne~gjc(I{Oyd<uY)-|y~y=yRGO|WP}p>+a8aq}Q1'
        'u4A)xEb&SQ@o^$vA>tDq#3zXOI1!&F;uRu3NyI0J_}&iU(?ooNh>sKTaUwoJ#HWe)VIp23;(LksF(N)e#E%j2Ng{rVi0|(pew>I;'
        '6Y*z>_$eZOkcf{H@y`<RQ$+j_5uYI9=ZN?W5kE!54-@ezB3>cl&lB-yiTG(EevF78AmS55{0b32PsCp!;%ABYGerCp5r2w^?<e9D'
        'E#d`Y4m7klPdOY?-!6wc`1^9~H$VE$qkH!k79W1_laKCv`{R2*d-%(D0YENC+mg6i-j6B<B=3DOEq*KR`;ZfLUUzs!gAydXEeF*%'
        'F%heE+woLG4-0Zcb#33Na2PN-94*LrGKs=8%8>1fQ1I*(@#$T-@MD+Y)Cn8QlH}V$v$nUPmwL-~b}Sn!gmlq?nxtZzujSz8_qE-M'
        'W`%O3;=7(*YgG$yc6$%28c@)zYoID=t879!d8D>k$j)a;rHAQyR27<wmjTudZd8wjx4>WHkAD8)qX!4YYip6WK6>}guOB=J<#5A4'
        'Q5k2!OHtkPKUvb>ZV7C@S!Z!M+3=a_*{WmPUSkCp(mGTef0`427Jm_c6@L?d7yl6d6#qiAyWbd)K#Q6VmTZ3_%fe{;yzy1r!f0Au'
        'b2nBMn7Y9yxVhGw)$y339IAN*>ce`p9#n*QA+ZB-9lmfKiLd|<e#~9Grj!$KO+nLqUY!LsEai6_i_jIrVnmFK30!?z+~?wV?L3O#'
        '-xhx;h(C65j`(*~0p-;gH0Y>m96AurY7ah5K=aw7RUH5|#{>q75WWX~^}<ahB`4tAM3uXv3a;rOqMCkIj^2dSv~6+yn&t6r?i?vX'
        'DW_ayF-#JWS->aVB3_+t#-n;B+S(`b#F4O1Zoz5ek1NI!>Q1Aa+Eij4Nhd`~r-1QFVZ54|!)*kv5o#RFbQx?^Y=iK}#)U)Ua`Hky'
        'nKmSIPxkjD(h{~9Y31ixIa2y>e$7T69g+zs)ji+E>rug6JS9_bFtC32TJOwMztN(;LqT6@{f1h)xw^VuDuI^j8%Rb$&NORhC_!M)'
        'Sc4q--;vsCoIA~It|AIhImDux0DV<0x0Za|`eVhbTUR&NZ>(>X)b+2ft`~1yd$rIqq*`sh87;7IxIlEGsw$p}uVJ%|O$8edn>sX~'
        '>YTmtS<hMOFuadFXx-1lk^8ChD70NW;Kl3kJ$mWL7oLE^uJENmNs|7(H>1#AJyvhxhN8qw2sbBDK<=XZ-oxg7Y{E|yhTH##>+Z3>'
        '_siM;00wrciRlmk00'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
