# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zhangge/worknote/ProtocolV4/uavcan/custom_data_types/dinosaurs/indicator/beeper/Paramter.1.0.uavcan
#
# Generated at:  2025-06-25 01:48:14.996222 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     dinosaurs.indicator.beeper.Paramter
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Paramter_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     persistent: None | bool = None,
                     volume:     None | int | _np_.uint8 = None) -> None:
            """
            dinosaurs.indicator.beeper.Paramter.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param persistent: saturated bool persistent
            :param volume:     saturated uint8 volume
            """
            self._persistent: bool
            self._volume:     int

            self.persistent = persistent if persistent is not None else False

            self.volume = volume if volume is not None else 0  # type: ignore

        @property
        def persistent(self) -> bool:
            """
            saturated bool persistent
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._persistent

        @persistent.setter
        def persistent(self, x: bool) -> None:
            self._persistent = bool(x)  # Cast to bool implements saturation

        @property
        def volume(self) -> int:
            """
            saturated uint8 volume
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._volume

        @volume.setter
        def volume(self, x: int | _np_.uint8) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 255:
                self._volume = x
            else:
                raise ValueError(f'volume: value {x} is not in [0, 255]')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_unaligned_bit(self.persistent)
            _ser_.add_unaligned_unsigned(max(min(self.volume, 255), 0), 8)
            _ser_.pad_to_alignment(8)
            assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 16, \
                'Bad serialization of dinosaurs.indicator.beeper.Paramter.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> Paramter_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "persistent"
            _f0_ = _des_.fetch_unaligned_bit()
            # Temporary _f1_ holds the value of "volume"
            _f1_ = _des_.fetch_unaligned_unsigned(8)
            self = Paramter_1_0.Request(
                persistent=_f0_,
                volume=_f1_)
            _des_.pad_to_alignment(8)
            assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 16, \
                'Bad deserialization of dinosaurs.indicator.beeper.Paramter.Request.1.0'
            assert isinstance(self, Paramter_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'persistent=%s' % self.persistent,
                'volume=%s' % self.volume,
            ])
            return f'dinosaurs.indicator.beeper.Paramter.Request.1.0({_o_0_})'

        _EXTENT_BYTES_ = 64

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8UR7IY0{@*<ZEqVz5OyH79j7meOjGzmjS8tzr7H!*`%7s{rOJ)5l9CFEcC~jmcvd~{UU&D5T?vVP05#G|RLb)I_$kcZ)sEA~'
            'Lc)^e@$SwuGtWFTzpwuNPrX)t+{JvFnly`;0WEkYp71z>h$U*2D<dp;cjgvkVnk+oZ<>QY^zT3Qzxl4KGa)5tk2QB@&*~zvg@)r#'
            'PBF<x1aT!5QW;)o6A77$gj=Pf7$6574Y=kbOU5odF2GptnrsZ(2qgn_WB-MH=zA-@+MoWZck7H>t3_N`F#Z9>SyIIOm3OCZ3&_%='
            '%vvnvmNOgDUFM$aP_`J;i}f2yWx(a}^43`_EXzO+EmC#_ns8&;NTuNMEw?q80R*?`Cf)6XE2^aShu`(?4Q4EtDc9*D&_NMn%eC@Q'
            'x3M6JkyVze#JifOtMgTGe3K%yf0RZHC8T$xg(2u;>EYYGCSJr#`0le3u|8H=LEXS@yj;ZK+6yeQcv`h8_`Qc)7-6@d`clX>P`e=Y'
            '2ktEUMNA-Nxzd)2)c4&cGpf)D&_xC;=aju`gr7{r-mMKtL6bo^JtVePu2LbWf*u-AkjvqatmdyuKawi6s5Q{aszhb`AA46X_&DLx'
            'yUnC9R*jC@We9jKC$i^)BBx4H-nHkVx)yy9y@0ZT@-{<mC{s<mhIWrd0{$6pyR&;>JEa?t9|3Qagj9nd>2;;F{|w!ng{CTJiUxO~'
            'B!^kWv{JT2HaVxz_(>N(#n13_`~ttkukdU9rp$Ad#TkXzo+<N4AC$Fy`M-CkZwPz0{7-evB;a0WD)+9l48%-FvC0G~tGxpwMY^{%'
            'X+KaMWl;;0o}i%V!TavqfTu*k@RdjSGyXKU?z{6hl?=L(CqlZl3X!@HSY7aZxPWo4Ut}5A(^tIfY|OI){9nG?TX}9`+8BA27ENIh'
            '6L}*c!$6Y3C&6fhp)4{Uyju(=IhW;9>C<G$5)>Z?v?if}iP84fu%PdlE+*lT={1XRyg|ns^J5c-$-;F!jT^WbD%rv=;MK(`!fOZk'
            'VIMy_q0{&+UdQi3zws7n5WmOU|6gOcvrJ13D!AMuJGIx`7R_|E&NV~eDgBg75U<R)Mu)b>JH3^#qN?37z`cs2{e@1Y)zL6iy+~n)'
            'C_E;G3%fMyuuG|1u}oi&szzNWhnL$CXzyb|xd+;N&2V0OZc6^kR)x#X375e&`WJ4)j#29d000'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     state: None | int | _np_.uint8 = None) -> None:
            """
            dinosaurs.indicator.beeper.Paramter.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param state: saturated uint8 state
            """
            self._state: int

            self.state = state if state is not None else 0  # type: ignore

        @property
        def state(self) -> int:
            """
            saturated uint8 state
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._state

        @state.setter
        def state(self, x: int | _np_.uint8) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 255:
                self._state = x
            else:
                raise ValueError(f'state: value {x} is not in [0, 255]')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u8(max(min(self.state, 255), 0))
            _ser_.pad_to_alignment(8)
            assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 8, \
                'Bad serialization of dinosaurs.indicator.beeper.Paramter.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> Paramter_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f2_ holds the value of "state"
            _f2_ = _des_.fetch_aligned_u8()
            self = Paramter_1_0.Response(
                state=_f2_)
            _des_.pad_to_alignment(8)
            assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 8, \
                'Bad deserialization of dinosaurs.indicator.beeper.Paramter.Response.1.0'
            assert isinstance(self, Paramter_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'state=%s' % self.state,
            ])
            return f'dinosaurs.indicator.beeper.Paramter.Response.1.0({_o_0_})'

        _EXTENT_BYTES_ = 1

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8UR7IY0{?|mO>Yx15KTqWgqE)=6&xuXP=I#ZBF-E@LW0mXYN0n|*=rM9?Aj}Tgrrg>dH@y45=b5XFXK&{mZFMWGT!mLd2i<V'
            'YxDPuW~2Va`_+UyUSz}xt7xGPC@Vxpa#L2uDK8-2-19c%K3MU7QVBSL$477oz1Sj}mY84VN*hOmb(zv!<<uLSF(E2pvjMfV^cd_4'
            'R~hZ_dWVdJb;@Xvjo98ljZdII*Kd4>BZ!NHdT$jAUO4y&S23Jjg4lYkM8VIQEf7vUB|g!;s=TtQR9=nnM)!kuYN!Q&qrDgk`?t(R'
            '!jvb4&_gew-$C%4I!{W&1<2)icW?%j%Cc9O+e#@E)c6Lw5SNMbRC8+iMWExrWGl8Xl>{^iH#x)x1V&@`f_}m#(<vW<T#-u-*>F)='
            'fkPG?e#BeklNt+7Dq}rS9Jb>UaVFSYV4@JDqS!08(_f(&#OniG>Ufa8o}jk5b?hxo+G6`aQav1|1${C0vo?v>!oV7Da#QR-hd3YT'
            'D5o0YQXZT)<@t~u0?$l<@yrHTG&KSad1i&pY$H2`@@YU_BB?{BR%oA=G*Y>MWBEWnjCX4BQ!{EzCqMN5->Y-h3&WZ5M7&pzgLp%%'
            'F}{X&6~$)qNl!kNt8z_da$Ro7P5G>5)+DUJ9*@o(biP02=`Wul-gv3}yZXF`$5RKzYs6F#SFQqalaiT2;rhE<qBQ7Fj}Kx8h19BM'
            'KAb1HROoW~Hr^gkjx!kkb4l)`>~<&$YA2Voh%ll>5bzUv{mw7P@F`YPAoO)$D7REPSsVj8PC+}_JQOrlFAy=VsIFh@c3_SLmi+;w'
            'lPE_?1ONa'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    def __repr__(self) -> str:
        return 'dinosaurs.indicator.beeper.Paramter.1.0()'


    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8UR7IY0{@*>TW=dh6m}qqH|ZsbOjC&puvAo~BsD=)fW)mNrBX35Rzf2r3ZvQG!DrO<%rY};?4U~Y0n|t%Q7OaU;DHBz1_JSi'
        'IJ4_pTwA2IWO;UG&h0zjch*16|8}@k%0KqCv={3*sS(W-rwKozVZv%8lI>J#ZkV&@4w&ljh<({hnLBaUAGwEa!(JeYeV;LHi1GVS'
        'vKMZ%gtyToK7DhMa3Pq=uN)YaMJ7`d&K8KEZ49*;b0Ia&l&*0R^N1R$Y9V7OQ?({lv~6&)U&M7bARVSOm%_U)ANJQLu0B^U{o)>B'
        '=7bufc$gWc-8UF#MzO<N&Mw^HEQv>%Et8lUTGTkpJXOAI-tk!NNSQDyPM3F%gxrvXiIxG(4xL66fosbcfqT`iHwO;9S#1~3_WTi6'
        'Qu^8LJNpvRhKiV~c-+x(7Q%{MPJP|lFoB57lUPR1mK+|vTm*+#Fhb>?(7YvBd{-FOV(L_SaJ3%5>#zaWALkwyJ2J_z8?XsmS;%Z<'
        '3`G+5idK2MH{c4q4L35ZFJ`G?*e({kV|$T&$Ga>hsZ@sW*fs1L(K1sJ!-Is8lw$U_?0*s-I=j?FrgfWs_XN?JdlL%*>G@DT0xDW9'
        'Tm?T!^*~79qUENNMn*C@yy@&>MmrG|&aOq7HnKfxmqy1!I^lXqC^RZ4<!oh0s<&#}wZ1FkA+Hdi8Z%Xht8cd#fO`y^_Tm9E)!dAs'
        '9Xejk0VxC{@OHtp{|y}sLSvN!Ml*Xk2ZtC*l$0j-tW%1i;r$Kx06v6|;A6N2pTG|6=6TMOFu@Sl2Fx7s1G6@h&(5CT;pX%F8S5BO'
        'z`jUi>TGqE6WwcvGU3Rq${uS=<h?<qeSvl4MU5#v0*>l|`*x*CV}zjf)Fq(s?QnJ9UfPwy^F~Z{X_pF**aeU3m}NBPW2KQL301wP'
        'tQSd#CK+?Tx{dnW6CL8jNQ<;kg;|K;wYl(u#0Bm8McIooOQ^SACajxMkq?yyDnsW^q2s*;=#A+Rdi5nZ!talG@X%lC)`QG%uj2OV'
        'a9f97S+ELga0%9ZC0F1EgPY?jf_IML-3GijrPFX5K7~8J-*6W>2%kay`8fvrv$#~og7Z1DS9-y&qo#{-t_Uz1<4-Z@w}(@sic{lS'
        'ea?@lVs_kvuL_L59_th@wh~|UID}P%@Dvp;@1xe)KBjK?EPg#G8g&Z|Cfng*Z@>}e?qRP7e!uiY=lJKX@`u$ahu#!tmO`aTp;^Do'
        '^Zm?L?AF;{N`<u>w0La(Zcm@H3pmuxV9Zia2KW>H(9ghwt!L*!Fidnd5vKQXq_|1sholdX^uYw_?bS2D=SIR9!4{x#x&J4lkJ8xb'
        '?|2%hA?n4us!-J5@E80G|D07($Iqpx+3;my?LWBo1<GLw000'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
