# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zhangge/worknote/ProtocolV4/uavcan/custom_data_types/dinosaurs/sensor/magnetometer/Statu.1.0.uavcan
#
# Generated at:  2025-06-25 01:48:14.744388 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     dinosaurs.sensor.magnetometer.Statu
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.si.unit.duration
import uavcan.time

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Statu_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 timestamp:            None | uavcan.time.SynchronizedTimestamp_1_0 = None,
                 data_update_duration: None | uavcan.si.unit.duration.Scalar_1_0 = None) -> None:
        """
        dinosaurs.sensor.magnetometer.Statu.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param timestamp:            uavcan.time.SynchronizedTimestamp.1.0 timestamp
        :param data_update_duration: uavcan.si.unit.duration.Scalar.1.0 data_update_duration
        """
        self._timestamp:            uavcan.time.SynchronizedTimestamp_1_0
        self._data_update_duration: uavcan.si.unit.duration.Scalar_1_0

        if timestamp is None:
            self.timestamp = uavcan.time.SynchronizedTimestamp_1_0()
        elif isinstance(timestamp, uavcan.time.SynchronizedTimestamp_1_0):
            self.timestamp = timestamp
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 '
                             f'got {type(timestamp).__name__}')

        if data_update_duration is None:
            self.data_update_duration = uavcan.si.unit.duration.Scalar_1_0()
        elif isinstance(data_update_duration, uavcan.si.unit.duration.Scalar_1_0):
            self.data_update_duration = data_update_duration
        else:
            raise ValueError(f'data_update_duration: expected uavcan.si.unit.duration.Scalar_1_0 '
                             f'got {type(data_update_duration).__name__}')

    @property
    def timestamp(self) -> uavcan.time.SynchronizedTimestamp_1_0:
        """
        uavcan.time.SynchronizedTimestamp.1.0 timestamp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, x: uavcan.time.SynchronizedTimestamp_1_0) -> None:
        if isinstance(x, uavcan.time.SynchronizedTimestamp_1_0):
            self._timestamp = x
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 got {type(x).__name__}')

    @property
    def data_update_duration(self) -> uavcan.si.unit.duration.Scalar_1_0:
        """
        uavcan.si.unit.duration.Scalar.1.0 data_update_duration
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._data_update_duration

    @data_update_duration.setter
    def data_update_duration(self, x: uavcan.si.unit.duration.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.duration.Scalar_1_0):
            self._data_update_duration = x
        else:
            raise ValueError(f'data_update_duration: expected uavcan.si.unit.duration.Scalar_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.timestamp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.data_update_duration._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 88 <= (_ser_.current_bit_length - _base_offset_) <= 88, \
            'Bad serialization of dinosaurs.sensor.magnetometer.Statu.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Statu_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "timestamp"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.time.SynchronizedTimestamp_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "data_update_duration"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.si.unit.duration.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = Statu_1_0(
            timestamp=_f0_,
            data_update_duration=_f1_)
        _des_.pad_to_alignment(8)
        assert 88 <= (_des_.consumed_bit_length - _base_offset_) <= 88, \
            'Bad deserialization of dinosaurs.sensor.magnetometer.Statu.1.0'
        assert isinstance(self, Statu_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'timestamp=%s' % self.timestamp,
            'data_update_duration=%s' % self.data_update_duration,
        ])
        return f'dinosaurs.sensor.magnetometer.Statu.1.0({_o_0_})'

    _EXTENT_BYTES_ = 11

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8UR7IY0{@Ly>u%h}6<*1@tz=tvW#{TR<0Q4D#$t5YmDg$0)>UdaWxN(5#TD8l#E=~AjKk%yGeb$MHbC<ug#{4E0%n2y?Y}%i'
        '9w9(qAde9A3G%b&ki*r=mVg+rzO$U+IcLu0JHvmD{ri*ITJbM?J?Vuyj2urhC1@lLsUI=N3uHHuS{RmR7q*N_1CuJY-Ah>hG++EO'
        '{~}+=#=V$!Vg1ce#8T5#X-BhIOXYNFCuT-=nPJM=GSsAbHs$RxrG<=hUdtvQS@~)1j<~gd<zMF6j7N=8!cPs;`KO@&49^C;@@)K`'
        'U{QGN(X<y*Lp_6T^3n1kAJ1;2bT6Q>V?>uZTfI2oO2*=lh1>8z8`@2BKFRBqC;U8E=a=m3b7%RHDA5&0?13M1AIDn2k;4yS!#Yfz'
        'jMI$g3*$vB?iilCE$}j++IU?Vf|u8_7d9(J_?oi;YY%V<L-SSsQJ!7#z{fbGDjZgHl=^VAnXU+w)GUy3m}g^ND1&_Gf1|b9HfJPG'
        'yFODy?vkNhnix(E;dGCYglf$~qD34qq9I>|Dlnm_>X9z|j13Vn>@Rj2XBw5-=b%(7(ShX!;V|b`u?quCe5%<Z5t@W-S3pci!qgH?'
        'l1K#9K+YY4YJyZL)H8SmEv1@GL!yY!h+=<BAvf^)u9Dqj?Rt>DLK*3TV@%y5nz3S2AVIHA;GiPzz*Ds+;B18}qOd*<rvT^nXp}Pa'
        '(nu1sJq#24*^T6W>EB?zxxNG;A^Rc(KUqM*$9Jcv30WempEcJ{Mi#bHU#5nvuC|(_$Eeb`$UYYV$E5@^XL=5~OV%5O&Y^d~?-XiB'
        'k$ss)As7M+grsrI0;V-pBI=bcKp_xe^uSvP8@vYIVn&)^)o__=+*O!|<uC;mgn~6t%nk&^D>hKaBv3*N?UaYvh@ciku(WZvO%`Hl'
        '$i4R$2~<K1u~c9$pbCm2O)y@!iQj`JMT-gTMUoadhC~4!IECZeRjNoA-S5C=&1n>2hOyi_5nC#@mnL@EaiF>k9+Wj|26=#@m^WA!'
        '7z2f?F(igS5Vey-BV5d;He`%#Vg`N3=lFFi-Edp{4gQu}!+zrPW$R3S+;-a!|J=^`Vs`T{Ovz_W7xe~t!)SaS%l+8Nvk9+oD9>K2'
        'NP!(BP;f|QCn#a+qoO`(RQbc3SsjiX;8P9j_pA)-*~oH^o@qbzSvEJsgPz|jNfuABz+d5Od?^J&2^koLc4A?ElwI_8#Q_UFOq3_W'
        'yq#V4v`kgNU?E~&LV+%_NrXuFc~;*9Vn5i#r%!>NM&1G9;1Zd9@(=>s>7e`jQo)&#WT!WkG%}FUqXwM6q|!WlHA#KwXiu?D8lfY{'
        ')T?ve&c-l$d3OC&x^-5ZWe3BT8zi_nk5dh9A|ZITW%DCQ%YWM?1)yqzs<D265u^fsz_4Q_Lz`1*VS^qo6+NPdY!+E8j6&@gexm0<'
        'fsE3U6$(-~wgW%7=y2#dh_mbh<%QNTR<JKY6Yy2V%SBi2!5*oWbix9$D~2i`M#kq1YUfgs%5t*C;CVUa1`)LpyL$S7V%dvDB0VEL'
        'C8a5J>4ZY0`27X`0sj+s`G@=gZ}W$|U4(Va^CPIVn^mPA4-W{kdG>dno&SR{9~Qs2*r1KFbDm7{jGU!J_qx7>LVzqjU|nfx`62KD'
        'HBuc9!3i(mKtMTX+3Y3_k)5C0#2@2oJB=b3K+mr7=GXax+v;l{t`bS9A$O-zAI{koF%DJ`=m83oI9#DD;Wc*(U#s;sj9q9|XmISg'
        'cIsoZ0Sna4@f~0>t09>TCjZbC;<~*;XyK$VNSrWL<uKa{D0uta{b5MSwXA**IMSTB6aXa=prlnk{{$Sv`;ssz-Ur^x=GPj_tF6_w'
        '#`^kNtGU{0HSe@mR&FmhR$6O~R-?JHerL7WXq1#uoMFPwf4<27k@}S1g=l@vztVi;h`-<Fe>|l?vQaIdLhvlm?A2-VY_>el$p+=y'
        'N2r=VI#I7@Xqd1OVf?RW6ej<S(=w$Y?+h{@4Wwi!-vsi_4W^l=5V1Y@zYn|Ikut09sKs-LqkVVG{vNl#CoE1Pj`gc*aO;TUeRtZf'
        '&md0s-Sdc3efI+5MBlw=-<!4jF4^}lBhL2SUm#xWyK{&a`tB9P^L_U!;!NLt!RmbxvEFxIvie^}ob0==SUay;f38`3uOXi6yVtGV'
        '*AYkhF0uA+l)-V|u=u9Mw=DkB;!TV578fioTKtv8w=LeXxMb0>_>RS8iz^maEv{K?ShUG=*Dc<**s^%X;=2}qZSgl2-?R8zi@&q@'
        'dyDri?pWj&4=g^h_>IMHEq-V5dy79<{L$i1B|exMvBFE0uuuuDO1NJMJC(pI;h++pRKhov@NFf0R|(%&!Vi`3V<r4#g_Iv!q2jG8'
        '#kfrq0Ok$4uVes*46wle&M!Zn7^&6x7wH*HkX;T^4c}?QvpcH~KId{|7W|-t*)aS`2cxX`s4G~)(!p~)@pIISm*0lZQ^n&c@cVHc'
        '{`?%m=nRdIt8fp*i&1>)9LnnD7=oJy4&PI?@d4kofNxsJH~bI=2LBJ!_;d%J?i@d@HlKWqS#tgl>{(gEXAb}X'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
