# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zhangge/worknote/ProtocolV4/uavcan/custom_data_types/dinosaurs/component/ParamsSetting.1.0.uavcan
#
# Generated at:  2025-06-25 01:48:15.007758 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     dinosaurs.component.ParamsSetting
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import dinosaurs.component

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class ParamsSetting_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     component_id: None | int | _np_.uint16 = None,
                     value:        None | _NDArray_[_np_.object_] | list[dinosaurs.component.tlv_1_0] = None) -> None:
            """
            dinosaurs.component.ParamsSetting.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param component_id: saturated uint16 component_id
            :param value:        dinosaurs.component.tlv.1.0[<=10] value
            """
            self._component_id: int
            self._value:        _NDArray_[_np_.object_]

            self.component_id = component_id if component_id is not None else 0  # type: ignore

            if value is None:
                self.value = _np_.array([], _np_.object_)
            else:
                if isinstance(value, _np_.ndarray) and value.dtype == _np_.object_ and value.ndim == 1 and value.size <= 10:  # type: ignore
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._value = value
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    value = _np_.array(value, _np_.object_).flatten()
                    if not value.size <= 10:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'value: invalid array length: not {value.size} <= 10')
                    self._value = value
                assert isinstance(self._value, _np_.ndarray)
                assert self._value.dtype == _np_.object_  # type: ignore
                assert self._value.ndim == 1
                assert len(self._value) <= 10

        @property
        def component_id(self) -> int:
            """
            saturated uint16 component_id
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._component_id

        @component_id.setter
        def component_id(self, x: int | _np_.uint16) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 65535:
                self._component_id = x
            else:
                raise ValueError(f'component_id: value {x} is not in [0, 65535]')

        @property
        def value(self) -> _NDArray_[_np_.object_]:
            """
            dinosaurs.component.tlv.1.0[<=10] value
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._value

        @value.setter
        def value(self, x: _NDArray_[_np_.object_] | list[dinosaurs.component.tlv_1_0]) -> None:
            if isinstance(x, _np_.ndarray) and x.dtype == _np_.object_ and x.ndim == 1 and x.size <= 10:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._value = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.object_).flatten()
                if not x.size <= 10:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'value: invalid array length: not {x.size} <= 10')
                self._value = x
            assert isinstance(self._value, _np_.ndarray)
            assert self._value.dtype == _np_.object_  # type: ignore
            assert self._value.ndim == 1
            assert len(self._value) <= 10

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u16(max(min(self.component_id, 65535), 0))
            _ser_.pad_to_alignment(8)
            # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
            assert len(self.value) <= 10, 'self.value: dinosaurs.component.tlv.1.0[<=10]'
            _ser_.add_aligned_u8(len(self.value))
            for _elem0_ in self.value:
                _ser_.pad_to_alignment(8)
                _elem0_._serialize_(_ser_)
                assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            _ser_.pad_to_alignment(8)
            assert 24 <= (_ser_.current_bit_length - _base_offset_) <= 2984, \
                'Bad serialization of dinosaurs.component.ParamsSetting.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> ParamsSetting_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "component_id"
            _f0_ = _des_.fetch_aligned_u16()
            # Temporary _f1_ holds the value of "value"
            _des_.pad_to_alignment(8)
            # Length field byte-aligned: True; all elements byte-aligned: True.
            _len0_ = _des_.fetch_aligned_u8()
            assert _len0_ >= 0
            if _len0_ > 10:
                raise _des_.FormatError(f'Variable array length prefix {_len0_} > 10')
            _f1_ = _np_.empty(_len0_, _np_.object_)  # type: ignore
            for _i0_ in range(_len0_):
                _des_.pad_to_alignment(8)
                _e0_ = dinosaurs.component.tlv_1_0._deserialize_(_des_)
                assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
                _f1_[_i0_] = _e0_
            assert len(_f1_) <= 10, 'dinosaurs.component.tlv.1.0[<=10]'
            _des_.pad_to_alignment(8)
            self = ParamsSetting_1_0.Request(
                component_id=_f0_,
                value=_f1_)
            _des_.pad_to_alignment(8)
            assert 24 <= (_des_.consumed_bit_length - _base_offset_) <= 2984, \
                'Bad deserialization of dinosaurs.component.ParamsSetting.Request.1.0'
            assert isinstance(self, ParamsSetting_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'component_id=%s' % self.component_id,
                'value=%s' % _np_.array2string(self.value, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
            ])
            return f'dinosaurs.component.ParamsSetting.Request.1.0({_o_0_})'

        _EXTENT_BYTES_ = 373

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8UsYRZ0{^vFOKclO7`EG{agwHWn$m=47my&WD$}%SXh9&gm5Pc<FbS=Y5FL$oC;qot?=Ca5Zd_4`N`M+^5JepXQcoO^kT`Ja'
            'ffEN#95`{{gaC>6;{X>fNbt|@`WZXL5=4r29{>N%KmY3+zr5|Oo8y`IPwflqj&QsJ5sbUkb1%`d#|p#_s$n2p$+Q|@mOQd$#M!g;'
            'km>7s{}p{%&!{2d(<<)ocU(UZG~%KVYx&HVg%ahoDwdg)u3srEu@@sIq*ggnV_dj_uOXv`&!yw*x|l6yUei~!8Y5In?v^9Tgnj`}'
            '>0@70N~@vMF7uq0U8BUIk`if*?WZ1cx9Uo_h7yx!ec@Jo=A7{*t1#Yq$uUxPCGnVFk)Vrt1h=V>q#8I(!ydJ_)BrMSg;Th<V7Bl^'
            'nOF6aR(pt$)ORR%+JUY{Wf)RBn(iX5qt!Oz1h!Tgjhp%8c$ido_PIajw64|EIf|>e@>C3b!mM^)V4N_IRm~Z(LtsmaJfx<2#Z7uO'
            '4Z|?f2ng)JAhgVZz3J%oVjk{*dthI$tH8Z*U;8E6v~ulQxzJ=uPmKrD(Se@2Y6Qa&QrnevU9{Bh)URa4WI}q;PQAN|Srd;$dmAZx'
            'LaPTFu5CpIy)3)uTJ1RL%EZB#&<)qBtt1GwvigCDdbJ#QE=F{6fmH(xoWxvzI%J&6fVTp)o!H=F{=%ZV?Ns2~R5HJ(sJXO}<jgmf'
            'f%3Z+BhRC}zCm(3sZlRt`VBo(%v}>@D5cI=My;tO>Q~qj3z>BLnY2o(bPZjL3eU%jaK3>R`>*QynBiuCVhfq98a5>ndDQ3^vqm;^'
            't(Z%`5mpUb3#lI$`(jjPXwd}>%j!Zd3tle`2vN+Og;_F`+~waU)krK(B(0!|dK|yjW7eUAmcWMLS4NZh>_IDXeR(XM9!{pS^XdFZ'
            'GM}F_wYXE|FfOKyo3Y>I`0X|3JLpVfE}U0)H_`(gz?m=}=;%JVr8w5qYe1vU$O@;nS;ZX9oleKNud=h+BysGQmu_XqaL6$twoEO7'
            'S5kObSJ}e@;N(THA}><TTCIB{;E_Q90lVR?0Otk(++7X==>^nbd^5<S13+#OJt5`?fk@k07sSH@Knxk0@p_>g8^k?T>PIWoFgO-~'
            'AxG8=@^}-HsmV4LCgplU^alDU%)%ou4-y`QIz(^<F2kGfI^2M_;XQa4K7<e8Be)5lz{l_zd<tK{=Mi$K!!Y?xXLIzr+KFv?jX5L?'
            'c+3`yYJ!L$;x@w#kCBifLt^^k$8*cr_Dc8=Su2^<>)4#K4<S`TU|t@>mjGK?#gx&-fUo+2c@B)0cpw8i@XpO)BaCRxroL7ab|hp_'
            'Z9NUJwnmx+h~p-KX|)qcurOOVR7jPjA@WHARG@9#a2#@R&9#|cH-1$4*gvF+kUU)ap>H)5%hXhSPa*@tF?(YKfsBTs`E~}rgYV%7'
            '_z`}BpWzqy)ffOzz>`U|7CO55t`c?dq{@aaj=L?nvx(|+hBsQPfB&zN?ZlBs;=spWnAnQXy~r>?9#-)m382yUMcnr{P)@=Z(<nW?'
            'QTl?F&16!*J|gf;f?y%zSlP`X`pNV$Y6it;`a<TS&1B;8Jy9HmlU=2IIw{?r5pVZ;w@Gbcb~;)?_+|Jjwj+afTpQbHM~jZ%8S7(Z'
            '7Yj4^(tukqap4T!6Yh`Tt9AH#5x(h>z3`iw?)*8>Ra@};Rb=V|rl=UVL?UE0OU8;{iNcbBWqU3zjB5B}vkDvUI1SrG<L3v1KL@I='
            '|03(#6QP;!Ns1iDon~q;yg%03Y18T2GSMjf1IUM)F2D@{00'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     status: None | int | _np_.int32 = None) -> None:
            """
            dinosaurs.component.ParamsSetting.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param status: saturated int32 status
            """
            self._status: int

            self.status = status if status is not None else 0  # type: ignore

        @property
        def status(self) -> int:
            """
            saturated int32 status
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._status

        @status.setter
        def status(self, x: int | _np_.int32) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if -2147483648 <= x <= 2147483647:
                self._status = x
            else:
                raise ValueError(f'status: value {x} is not in [-2147483648, 2147483647]')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_i32(max(min(self.status, 2147483647), -2147483648))
            _ser_.pad_to_alignment(8)
            assert 32 <= (_ser_.current_bit_length - _base_offset_) <= 32, \
                'Bad serialization of dinosaurs.component.ParamsSetting.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> ParamsSetting_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f2_ holds the value of "status"
            _f2_ = _des_.fetch_aligned_i32()
            self = ParamsSetting_1_0.Response(
                status=_f2_)
            _des_.pad_to_alignment(8)
            assert 32 <= (_des_.consumed_bit_length - _base_offset_) <= 32, \
                'Bad deserialization of dinosaurs.component.ParamsSetting.Response.1.0'
            assert isinstance(self, ParamsSetting_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'status=%s' % self.status,
            ])
            return f'dinosaurs.component.ParamsSetting.Response.1.0({_o_0_})'

        _EXTENT_BYTES_ = 4

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8UsYRZ0{?YWO>Yx15KTqe^n(IXE8s@pfI@+73;Y6*5Gb@nE$R(f-nEG>y!Of;A*ob}9zaF11X73p%Xr%+ZBh2JW6#W+c{9)7'
            'n}1(68}%0-RAc6t%827uQY8;*u6RZYQ&z@F&mpevdm9QLEdMmFIGn<hV>p6toF|%==-*&c8%Kk6S)HZ1_F11=TDpDiz0`wjk2}0~'
            '7`#Y^+&XDAh(>H3oZF|+o9i`x!ZE}ZLcO;#51u>t472*11VNmCE4gCRzLp82o)Vv$ot0i$SxPU57}4IB1I^ic?fHP)s}xsAE<I6P'
            '54?b02cZk<JSh$1AlBpE{sl}*%if@GC%KSL;|J_PTqn*`&8TIUflfj$=Hmjod~gt(gqZ?j142&Y+9moVAD@l*2t-G;9k#=GWqCn8'
            'XYecDB46Z)Gg2AriDa-F+r*h*3yu!ONky?(Y^9%)ImD$tZgkX7x2H&MZWC(@lUCR|6jToeX+PhL{i;ox>vG>3ZwjLhUO`+4bXZW0'
            '<0^vlrku_g87xf{fc8WK5bs}A!FINlox}Jvoi!q;!!9ibr~M3N!Qn(a6p!ManmCzYB`I`g)>*w$2T4ry#^b$u48$8^jqx?Ct0)!{'
            '8(r~KJQL4FCN{;E*cLD9u9_rQi2wLPIMc;pkN)}@;?396f2hw`|3W(P1~C=H&MXi&E_0(Ku6=EXmj-3&@g01uxTW6MsQ?#9AtZ`h'
            'yo<N{lp+7Ye?ej=d3S?S)Q+!v5n)JG;P4x|z0Mz(;|r|LfS|V+a->^IowSVx9VMfc^c@sU*~^5FDyr*8x*KwrhdlcS->A7IJ_G;&'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    def __repr__(self) -> str:
        return 'dinosaurs.component.ParamsSetting.1.0()'


    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8UsYRZ0{^{NO>7%Q6t-#7I7yp24Q*0Y(5;{)ttz)^ODG`9pHzh0q*g+s3aMJgyA!{4*Sp)9*)%Q!Q6#EH8bQ@gfddCl2yx=T'
        'i32ANoH%gezzG2o|33$~aNy1EdhPfptp&o8?cJI8zIpS0=6mzXz%9sUqL17Y)NO9N1(Q?e5ZAd($}TOKmR}2e?g*;n=ptn+jzyoV'
        '2UOiu2d=1>)U@1cGI}wjT$n<SLq=|06fCqv$l4?aO^?(N=YZ{aJ|`jLg$UiFo+y+EBQ?HAg>bw|VIhW8GH0$(#vR|&z(Y&P^G#LE'
        '7Bg4X6*S5uLNKQs3d+@aT&2f8QYj?|PdU`Jn|6(uHW4H?zn6NzoSGw?6_l7b>v5;zQTtg>&<bViH#usS9bvlEs|ZlVJc3&UeN*#o'
        '^vy20v(y06YK5n9Zcb0(jxw*Q1tsq`xgefRnB59=EiA)`+>*M>bZjLDOxw4V%qX1P5ibu@a(9pYGe+u4PA(A~#gWqy@RNG9J)YF1'
        'HN8e0&!Gf)L{4^#n{ZbYY=N;xKwun$&@=~jCr|el^RNf*gZsN}1@^-Ot($1k%C&0c0-YsYH4Y_Dhr8;^VGKh+EJxH;(U98{znaTB'
        '6OxUt*V|jn>UhN317_LfO73sCwiy}pvS@!-a?4YWh#iax-EghkWcq=UMlTRvua$k*!H7=G(VCBe6PW8~0?LT+Su;SJO$!{%Us#ko'
        'p7uS92<mke)tlCmjC#5<P=4Ed=(>c}J0v%oE5r?{dP7YYbJuwp&L++{hgy>h#H-K+8c^Z%GU<X@Bdh3IRCpm81gn7+`LE`9nBn>X'
        '#pW_uIiyP>bcxn4X0>eQdNCLOhgdaqH6UJ8?DJunqD4N2C78=);bJ!p2vJP0g;_Ef@8wRDYB&-%1*xElJc<9tW5$s~2FC-#tBl0&'
        'Glz`O@x+Pb^=SM$Gn>30i{EFD>sp+UIgE=g<23dgEWde$dNw*!n+uk_r;#4$07kj?z`D~Xw-CjexD9C38D3_@(xaH8xl_qA&dcnK'
        '(n%co<;v|0844Ii#1e@mu$I8X>oR+^51c&rm&GN*X!Gdq1U%LcAmC|uJHX?80B$e)zHohFQ??Q0gMC2W#k)ex_5+a|Yi$q@^#L)c'
        'X~yk_a-tvi)QA@@6V2dQ0Gb?WH^_%mNGc~<SlBGrW1`p4kH9QE4v#_|o`9F(GF*jM;Z3*!@4`Fq0lWtv!H4h(d<>t#r|<=Q4qw5S'
        'A#$iqG5Ph$W~((hhR5_Owavh15nIg5ag+NYvnWou)C>qRB&IL^xlS36y%IJot0g^p6A!2CVWdj%b>}g38Sp5p=rX$GvkRWD+kuf1'
        '^M!Bu?$U8Q2t%@B5l_i+E9AnjHCqF$t>Kga@i`?hCC88i3p0fyg+y6sBA+mUaI}qSj^lCXq}H?_Wj^wcnIgoEOE2_InqsM(jP_{?'
        '-(;A*5dud>!_a&`4L`t-@DuzDzre5X8~m;ffYWd$j@H7u(|lWr*tk-q;}pl)rrh(f>Uqr@>1cHzo5}nS!mSLFM+U(zFo=!DzAw~N'
        'kcR-j$OH`n;1L0Ia8FDeQz$*vDP7%%iza|QL|`dKFpzqT?8XqiWO^7ijpEZiA#>qIGEp6$DvrQ2Z8cnsYq)FZTOHqSQi~WQPZtpW'
        'Ts4cvM5biWl<T9NrZlPf?a>~FwlOk=uQmQY*jb%NbeIm|n>F}$9=_|6$?%7qT7NZYt26lX8nX65U0{?MJQgz2@-d>0ksHD{EZ4z-'
        '5e0v3RBc<=t%gTN<0?Yo?|v%nKTQADj7Sqd&Xtomljiu``=ia77M-@Ks3RN0TN}qcbK247AH0+6S*)u&|Ge(_Te_@Wa(uDp^$63{'
        'Sl9eumn1@-WCqchQGF3DuZH-;H_VG_2}RNjKz8aYthsax|0=Gnp)%S+h35f&TfL4O-g{f;rao=GMdfsVmfW*D8r$kcT}F62Vrf`f'
        '3azTNKX2%txAe~~UD0>yS>&tgqDJq>xxGCamJ9y?>NaQ0a}WRk'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
