# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zhangge/worknote/ProtocolV4/uavcan/custom_data_types/dinosaurs/bootstrap/updatee/WriteUpdatee.1.0.uavcan
#
# Generated at:  2025-06-25 01:48:15.098073 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     dinosaurs.bootstrap.updatee.WriteUpdatee
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import dinosaurs.bootstrap.updatee
import uavcan.primitive

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class WriteUpdatee_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     index:  None | int | _np_.uint8 = None,
                     offset: None | int | _np_.uint64 = None,
                     data:   None | uavcan.primitive.Unstructured_1_0 = None) -> None:
            """
            dinosaurs.bootstrap.updatee.WriteUpdatee.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param index:  saturated uint8 index
            :param offset: saturated uint64 offset
            :param data:   uavcan.primitive.Unstructured.1.0 data
            """
            self._index:  int
            self._offset: int
            self._data:   uavcan.primitive.Unstructured_1_0

            self.index = index if index is not None else 0  # type: ignore

            self.offset = offset if offset is not None else 0  # type: ignore

            if data is None:
                self.data = uavcan.primitive.Unstructured_1_0()
            elif isinstance(data, uavcan.primitive.Unstructured_1_0):
                self.data = data
            else:
                raise ValueError(f'data: expected uavcan.primitive.Unstructured_1_0 '
                                 f'got {type(data).__name__}')

        @property
        def index(self) -> int:
            """
            saturated uint8 index
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._index

        @index.setter
        def index(self, x: int | _np_.uint8) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 255:
                self._index = x
            else:
                raise ValueError(f'index: value {x} is not in [0, 255]')

        @property
        def offset(self) -> int:
            """
            saturated uint64 offset
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._offset

        @offset.setter
        def offset(self, x: int | _np_.uint64) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 18446744073709551615:
                self._offset = x
            else:
                raise ValueError(f'offset: value {x} is not in [0, 18446744073709551615]')

        @property
        def data(self) -> uavcan.primitive.Unstructured_1_0:
            """
            uavcan.primitive.Unstructured.1.0 data
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._data

        @data.setter
        def data(self, x: uavcan.primitive.Unstructured_1_0) -> None:
            if isinstance(x, uavcan.primitive.Unstructured_1_0):
                self._data = x
            else:
                raise ValueError(f'data: expected uavcan.primitive.Unstructured_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u8(max(min(self.index, 255), 0))
            _ser_.add_aligned_u64(max(min(self.offset, 18446744073709551615), 0))
            _ser_.pad_to_alignment(8)
            self.data._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 88 <= (_ser_.current_bit_length - _base_offset_) <= 2136, \
                'Bad serialization of dinosaurs.bootstrap.updatee.WriteUpdatee.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> WriteUpdatee_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "index"
            _f0_ = _des_.fetch_aligned_u8()
            # Temporary _f1_ holds the value of "offset"
            _f1_ = _des_.fetch_aligned_u64()
            # Temporary _f2_ holds the value of "data"
            _des_.pad_to_alignment(8)
            _f2_ = uavcan.primitive.Unstructured_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = WriteUpdatee_1_0.Request(
                index=_f0_,
                offset=_f1_,
                data=_f2_)
            _des_.pad_to_alignment(8)
            assert 88 <= (_des_.consumed_bit_length - _base_offset_) <= 2136, \
                'Bad deserialization of dinosaurs.bootstrap.updatee.WriteUpdatee.Request.1.0'
            assert isinstance(self, WriteUpdatee_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'index=%s' % self.index,
                'offset=%s' % self.offset,
                'data=%s' % self.data,
            ])
            return f'dinosaurs.bootstrap.updatee.WriteUpdatee.Request.1.0({_o_0_})'

        _EXTENT_BYTES_ = 400

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8UsYRZ0{`t=OKcn073KVCNw#S#wv{-x>BMoE#AcYpNtADuCM{Il9EWupR|Oi3hU8dp6pF(RhYl4WfU;<z00VRYPXR5p)FKNl'
            '1$3jOmRf45rIsq%0_xB0dmK_C^@;y7nn(+B=H36fm!uAPr_?|FIg@Dq1?Q@hrCO<+HEXu#SY_uct5CMHX3?Ffx;4kQqu}sIcG;QW'
            'm!)4#R_*9k^ujmM*HI?WO{Y?^y@(}(!=L(Iz3A6HyIVywE7k;ekt;bBw`SG7TDIW2e$Dr+YPMc2S-x#&f9-MKpS5nT*}tpXH9rcH'
            '=1tqHIc`PxH?Fs?Z$%_g;t$a`QP68zzVA7Ox^LH_&v~#tD%sSE0`2FHT`p~<*JJXamg$R}_cE_~qITyd*XaMOQgg;CcIg)t-yXBQ'
            '?pk}zg5#TIyE5jph?3lS(W?38gj=#B_GEA}-*zO-vLA98gosy^_<eLO3Z5`)zEvq%Ua8a3biKfO0?nzE>_!x*X2~r^K_cR(C*rtl'
            'fSqn#ouwgmjy=mR#74S%<3`Q)BX*HJ-=%M~u6lwqb?au)s$@5d%<>Z3tt>^Xj~!{_&5nH@ZTSdJ?*X>wS(8z4>bk{G`N_x4Dn1aW'
            '-Dn*)?Xo>#SNs_LjvA7iH3Ww^gjK8P_>&P5QgFNlig`n{afe}w8=fagfEk;sW}#e*f{X1`w_xR2``hoMpzo)SA1C}Nzip)&D5hJD'
            'g7jWaYLgQMx9sq)^uwNTIS@V{)K99mXZfzz`D!ULhYuh7I5_d4TPgBsuk5NSsur4_T@ho=^^abym&=wnxkFPoZ(8NL9sM!NP%5ky'
            '*wq#ozvNb@u342a`<h*~eP^$fzAz`OhQO9v{HA%zek+_Mxw9sK6HbNCr?_b9B?ChYbiHf|2P6sIL`ZV$S!q7=iIGE6TW8wl87ZWO'
            'q{sKNxHh_Eq>&y{vSoK@hl~uK7xiq~^AmpGyQ>}@qMnfYVp&qeI=rVI^-^C*N4os-Q+{^zdu`}29SJGbiV@PWJ8IKW-X=P}BNCVJ'
            '^ZvWCr(<+Hq$grsmCO5t?TNd#rG9!Mq?5bmz@=Pv>YjYj2|5|lKpSbE%aiwPPp4=gq^I`GiED8A>HG3aPtsE%J>7*DmvVn+?%N-o'
            'rl&(X`@Q*cEv|F!fnv}ZIvY}Y6I+q>`3Lq$=O`W0GqIoa_vJ65Kl@PP(Rq3%qzmns9eofeJ@?RJ(6e+Qq>Fd#47W&gZLa(LLyb+('
            '(Z!H5?K)dMd*PwSpyw$Q(u;RpC%54GFFlex=mmN)q)S`9y}*5DI{SP1k;SE#=u$}8d%}TRahsPPX-;&RvLWTR<{%SK!YhwFD!oj('
            'kY2rKM7Slldu?CxqgUwFkgn{Um`mJuu01uc?^`bP8eIwLjr+okTXWkt_cd2~o!$s(uzR|4V!qzm_dMuL8Vu>}`^JuY;P&r4mb~dL'
            'dOM_d_nyNmJjS4y#rGate)JB#8`Ap^gfI8Pef;FH)<Eyk`ymbOm|5QaI_JuEqiR)}6u+r~gp7oWgw8n!C6SboRI#BUsZ$Cm87UPh'
            'odz%<V?f1#jtzs-NXtm8Nb8hAMn*<OMyDKdGIA<%It^k_#-NHporW+ZV@So2PQw_MF|1-(r#$j9@+$H=jbKE^h>8)NMlmX5RK=)H'
            '3`_=7!E~ykDx<2Rs#60E84VQ;ou)7)V@k!8PSco{F|A@+rx2lxP(`TI3}$4^sF=}d7PB&DRm|!%hdCK@D&};W$GnVr74teRU_r)$'
            'iUpk(u_$9v#iCA2Sdy`%Vo9fEEX!C{v8>YyR%EQGSkY+}t1?zqtm?FeH5qFv)^u9Ox{P%d>pE><L&gTjlcOskp&+3lVIV0XsUXQg'
            'Hjt8#QjpS+GB6-vK*4~90Rw3XX$5HwX#*Jv83h>)83Q>9IR!ZlIRk?d1{Dly7&I^>VMxJ{h9LvP5{4BFYZx|=mylPG*N`_bB4I?q'
            'h=vgZqY_3HjA|G)z$7pQOan7el~7es)lfCikkC-j(9ke2C1Fazl!hq-(-Ni?Olz1n5K0IYgc?EvGZJPL%xIV~Fe_nJ!K{W^19KAQ'
            '6wGOuGcYe<UctPEc>@a)78ERKSTL|CVNt=NhD8HQ5|$J!X;?C_EMZx}vW8^?D-u=|Y$#aKuwr0U!m5H*4XXy$B&;b|)39b>UBbG8'
            'bq(tVHl(m#usLC8lwuB2NjCm}!>5yiM;-9#ec;on7>5Hs{RsFp|8G1-_o4FX^qoGV9|50EclY53%cs*@-+}yS__V0`0{5Kh?(dJ9'
            'PYX;k?MXP`)7$uT_rx6V>3ikV@w-fh%Tfn?`T_WK{Hb)nr}u+TZ@nY7_%!>DA9qq{&YO`;wmG!i;?O!L9)d{=65S-z>f@x*oIZ0N'
            'Ey%RGJB=3fxy7UpX!H-2M#mhQlj*yr(c+hCu_6)w6do@-SV4csc8FP+jQ3E!j@UYTy%zMECA;d`;y3tG^lfm&yx}zLl38^<-*igR'
            ')!>*}bL(Ew=7O?qRxO`JfgzsCP9X{o<=vXo$cxikQ6`XHjslgrV$a3+idmJhF@BZ&()GTmxMJ(1C-1qwTXf6UuS9_!Z(Kyd>1w@D'
            'c8aEFkJZZ}k*!^nTEuP#hdLHdPIPW%WM9eVvSJq@^2ORnzsal`Ptg;*6gAts=@jkgTXr#c_k&8h-eH&K8I<j!SOrMCH`0Ykj?AUB'
            'ogK?wN_*Cq>4H<SyvejPVU5|@C`dISi}!#k+;_ZVvzdNpdVO6>BX)4AiJ0lTrsukT(@(8x@wC`RhW&&6ll_bRoBfB~X8&ckMGfp{'
            'Y&c#%pso#uqj{@Taw=mxHW#?`lOV~XG{q4m>)qd^u<x#J&V?#qZH<M^{vxcOV<*`qmKh(A5(##>&i?u>``cCa_ifn)$BOlu?@n~~'
            'B{;OX$i%NVSDAR@TgyyQaH?yaN%X1(nW%JJ<sqkea|ZU%>WRj6t|FkmbEv*fCtT3powCP!MP=RPj6cQC#!vHyJs}_O=h97tw>t4@'
            'ta)8*qdW}d?VBd!C%KfQW)qXlp{*WvsSa_~_&c*<t~9)<6r0C0uuYQUlGtQ~564JySDS63cy3rP>tiXg^pxS#l3|zcX?C{29)DUq'
            'oDmOaTiCaUVEnu|-IsO;hG{o^{wj_z)fb%PZ-4PdpJy`LD)Fc7yHsg*j(rp_lI{B9?Cf%9kJ8;+NLK5r#6L-PT`^+pDo1~+PoUra'
            's<PH>L$hr{IJ=8bm}dV6Ft*vw#wY*)'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     error: None | dinosaurs.bootstrap.updatee.Error_1_0 = None) -> None:
            """
            dinosaurs.bootstrap.updatee.WriteUpdatee.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param error: dinosaurs.bootstrap.updatee.Error.1.0 error
            """
            self._error: dinosaurs.bootstrap.updatee.Error_1_0

            if error is None:
                self.error = dinosaurs.bootstrap.updatee.Error_1_0()
            elif isinstance(error, dinosaurs.bootstrap.updatee.Error_1_0):
                self.error = error
            else:
                raise ValueError(f'error: expected dinosaurs.bootstrap.updatee.Error_1_0 '
                                 f'got {type(error).__name__}')

        @property
        def error(self) -> dinosaurs.bootstrap.updatee.Error_1_0:
            """
            dinosaurs.bootstrap.updatee.Error.1.0 error
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._error

        @error.setter
        def error(self, x: dinosaurs.bootstrap.updatee.Error_1_0) -> None:
            if isinstance(x, dinosaurs.bootstrap.updatee.Error_1_0):
                self._error = x
            else:
                raise ValueError(f'error: expected dinosaurs.bootstrap.updatee.Error_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            self.error._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 16, \
                'Bad serialization of dinosaurs.bootstrap.updatee.WriteUpdatee.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> WriteUpdatee_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f3_ holds the value of "error"
            _des_.pad_to_alignment(8)
            _f3_ = dinosaurs.bootstrap.updatee.Error_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = WriteUpdatee_1_0.Response(
                error=_f3_)
            _des_.pad_to_alignment(8)
            assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 16, \
                'Bad deserialization of dinosaurs.bootstrap.updatee.WriteUpdatee.Response.1.0'
            assert isinstance(self, WriteUpdatee_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'error=%s' % self.error,
            ])
            return f'dinosaurs.bootstrap.updatee.WriteUpdatee.Response.1.0({_o_0_})'

        _EXTENT_BYTES_ = 2

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8UsYRZ0{@j(TW=dh6iz~OYm<;Dh)RgdmWPs}vTYJVfd^2UI$$~VT27n_iE5bLo%k%Qcb1viG_F8uAE;V15|ui<@W2xSB<{Bd'
            '#1j${5(tEN<RZZj;6HF??YK$mKyAtP>|DP2&Y3gcx0epQ`Oj!y{?QMl%}|E1OC%E!jiZaykC{sX-blHO6f=5!Rf#N6nP6+pl$jgm'
            '*k$vonbCtJp$#0L4WoohnhELpoGYmWP2DUFsbb7MClI67eyB2;@<igA5wgjIjCf+8PY<uR+c!+9ztnfdTsHa;p-PF!&lHp9yxEUt'
            'XOhu_%MpvioAeG6+>{b!Im1A!69)B>|6*GZf(rw~FuF|y#?Iri$@cQ;{dlAzYD6m9L>|+%L`L<5g~dd%IupB-c8K_qA~8$q3QTDd'
            'Sq4-p(%>PoyjR~{*#@%9+$9`4Ylkp1eXp6S(RUH4XcAHp?gYA;`54;ZCXF*>aDaq7FuKoR?}Q#%!j$70)gb}XaDTgXq%;W+!clmr'
            'g)rci3><@p^$=-e-M1Yt+e!tK_Lz1>J5r?z`)It44s&{RL(stXN*rHqw{cwepENcI>EmX{|BuUftz0U5=gOo|t$Nj*7R<pydlPt4'
            '4?ecAFu%|P;%M1hBg<Z`e5MOp|6C79BSmjtTK&CH8ed#mDy*)OGlg=o(2dr>?0gS!V?~52RtrmOUiCRd(@z&&<{o$Ony^NySm+2w'
            '!xI<mrF3}WP$#7d90gQ4DUT8*9mTOXj06i57frK=&D?A+!4=Eviz~%51b=G<OXpO<ts|X{C}xfo4=0jN!j*%?7KP3R7f6LUii$c@'
            'ty!`uk@_t(dO56#<>E?#ta%<;S*$)&=$7QUQ@teFtE~}lnXFb8m%5`p-b<2fQLff16|cJ1y#nTYfje~Cvqip$A$JFRq65bC^bV0F'
            'ezT?L7IX&gfmwJ2PQz2M0?)!aRN)199$thE$lztT1h2sBa0LuphqvLa3}r23s1E_EXlSnK39=Dwv5=%(C=!LHtfz?NnFtuMr%G(q'
            '89i+O;>b68w1Qr<Rk6J{P$c_Lpojst<}!Q{Xi~3RrMbYxOIR$}JXjH2@qowcj~YFc(anG+Mo$HqRJ?Ih_ECODJ8F;Zj@~0|Tk(ya'
            '%r)Pgbx*o&AZ2xSngEr^Q?Nu?t>26SX0BlgpC~hFFOuEBJ&2B$#meCucxiUjtHV<!a$$6Fhdi$>M@<mU`q|8FFdJ;S5z~kBd=bTo'
            'z<D{EOeyk#4`$#)_y|6RPvBGd3_gc1a`Fd=A0zD1ZSB746c~!y`)u^s=}4{Q&#SCs6Z#Iqk&m+<h-@}|9!F?2(`Q+OqZ8VAy*zNF'
            '-Eq7j5<rB;3_t2SD>THg>$gmTU+ic(i(@L9dq-jJ4Kq`kye@rwZAe=PrZkfI7-u6&tczlUZrR4Lb<!-RxU4i{m-Stj=&@*CG|68v'
            '%9)>EBy>yGGJCuunNQ&z+~{wZlJM>|c&`lacgZb$318{MyWVK_lns1+HNSJ;+};U~?ZmQPy8V8{;M;x97QTb;TUq%5e(EIe*G}ta'
            '_|2vUen(mO1HXUb%)i<}yZ-{xK12fe2><{'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    def __repr__(self) -> str:
        return 'dinosaurs.bootstrap.updatee.WriteUpdatee.1.0()'


    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8UsYRZ0{`tBTWl29b?3bX14{_tgb;>6$P!>N27>c80aLq&V{gqPuBvoA_70xetarAvvt%7Lk|VX1X-CQ^nW{+rsDCQCUv<<U'
        '_oI@fe$-!;)i3v>lBIr>pGx$jt=p=Pb9eS>Y{P;9H37+IXYYC3^V)mQ**#2%Km4>KQu^oZ%Z;b<sZ2u48;+%CtPl0!jFHer?6I7k'
        'w_GFeHeWKF>(+>Ic|2zXp9P0M4n7Lv-WJU<zEv>tuI93JGvaMIZ)B`7Vo5bp%9@qU8cvDilIs*k+=8=0n51R(G1{s<Wo7NWUU2e>'
        'VcT}|uA}D?g<MK^4I}ZcL$a@w-wcGC2VPXWZa8_%&NBJR)$;Ra0dNrcUhpxguj#JqSi=R^$OrGyW@}hnr3yUhf@Ne<HT5=Ww5c8%'
        'x)yuRVYXY>iDJi<Y~C8p8mZo_Ym6FBqph2@VawGrMt0OS1BjCF5uLm^W~a!D&wIO)6+w(GagK1vP-Ic$yTL%<J+0+kJ)6><RK1|d'
        '!mzo`ldNpYC<dOWrR<Twiv+a#Y`Cwv*Hp_-2cXM5XvWRMA(L!hyOuZHz&v6eZJ=*0KW+2&7WC^QdNxrtGC?L*LYWH8?dFb(zs+6m'
        '1vMGoo;959IQn?t?Y^qhDy>{BS#g%Fu1qr{V~iQuN}APdh*oXzTF8YteZ+Fd1B`IqQ)Q=U*H{?uV2lytA>f!ZLv~Rc&g28{P({_6'
        'TS;qo<@>;EeaCV`g)h<DvZ|h-*}1?|*AkK+9~-ta7DZ(T8e=v&!lgv*&l!&H+D`qaWyG{7`OL3*JI~qK5z6-Ls-(<nM(G$?mexeS'
        't*?;D=+5{Zl(KeR&lHT{lOPT;KR;|<Dm&vUaqS+^v!lj<kuzLtEtTHa#`GfdEpdFav})>1Sd@g795`lWDL>gmi7x6XETIb-oe2Pr'
        '(MEjW%dbM|l`@9+K`gIH)in@6^g#~a^Xyq^z<~s^579DT%N;mSNH5q_<);;Tzj;+UXn{>Ww1&7S+iT03bg&s(ec0L{msV+Q+qyik'
        '1-AMSEAQdM_PbKUHVP9wb;nMGq4gd2#1GryDIcB=X+^@fGTxo{%nLi<X&-j2ssmvOx4S7>uoHIq&{pv@>GDj|{IDC^e0X+Eorr?)'
        'd+tjvJOj`A@LYqx2ut$z-nTs11JC*J{JQ!Q718W_pgmwOJnw^A^)1tS{{u^eeW3dALMTUFPk*-ifeqOY_QMN49IWhF7YF907dLDV'
        'H~<HIICR&@5Qj?CMElZ)?hP-(As^xuJIgUUyy1JmOAz<r<$Jc1IEenpL(u~c!^=J#t;O~r$&A;>_t-<*7mmPD9}-RZfw+k0_(RnR'
        'jzPkQ_F5jq!%R5w(07I7(C$M=(;gvC;yd|B^n(-7;lrsrGv+ACZm(p`=|`puoP<+8ymDVYBW~h7^GJ1t)9{K9osHSm&hqQkN3I8)'
        'fleP@yKmo-1mb`FvFHu2!fQUfv34GwqCGlUF24EL^n=&o4IkcmApepSlJWLqwE^CQw|wZjBWEf41?rWJVouMNTKp0PMtF>f7?G*x'
        'fG9?JjEcA{VN`|~#(0d07?Yt5+jwjfu}#Kh1yoddR7F%}h+~|`xQKBX+OeI-b`jfU=)_JQJ4Ni2p$ofs>=Lm{h92zUu}8!n8IqXf'
        'F)3nFhCv+UaZtoT8HR9(#~~4iWH8a>(G<~?A%{60b0X$sC}NSvqKHKqCUAns2@xk`n8ZmQCq<l;!AGA*UqoMqn|PDQn<CznVG5^s'
        'oDy+LhH0GUaazP_8D?;X#~Bf4WSGTS9%n_Im0=F&c$^b)PKJ4$=W$-dc^MXPfyV_A7i3t(MIIMLT$Eu6mv~$faY=?-c#FqdBHohW'
        'Hs0p(wurZ7SjJ@@m&u>xT@E7xMkI_V809c3V3eG!V2s0<fH4VU3bt|BCSaR{Z3?O!ssgGKstU$Aj0+f-Fs@)bhwTEkOW3YpCx@K^'
        'c1qZ(U>Ap70(ME*rC<+-Jp%Sf*rQ;Q!=!*o36lyAayTg9poD`84skdn;E;qv3Yr|60-6$<3g$S>37C^Gr(lu8qJTvSiwaI~I3eJK'
        'gcAx*ayTjAq=b_S`W*TK`V#sI-sJG6fHx()so)fcQvyy&IHlk;htmR1OE|6I42LrU&PX_;;4Fu;0?tY}tKb}ma{|suIH%w|hw}o?'
        'OE|CK0*4C%E=ahb;39{M0xk=<DB+@lOB^l<xFq3{g10!lCEzUyZz*`2!`lMhmhiTM%bZ^rHmG4AgP57cSk$!tZ~Eyd>!Y6Z(~qE^'
        'j)i`B(oa8xewwQB(7PMjPpfykqaQ*)tv1Ht3)@etweLW_H2pNQ`5;M-H^%o%-A^;0#4DNbq@P~VPd8@FlYY9{emXp5;)IJm>8Br{'
        'pAK)OC;jxJ=%;HZV!59-Kd0sT7Ml8Ij7BRxG+*waWokTFC(WAZQZp?+&NiCbXX>L_GcB&(Mzi+0+(|!aqra$abl5{vGkwo(H2bBR'
        'jYxz)g@?lqy0@clIz$^D59d%m3e3NnujReXTFS^d2Kx;@72NQ)YS*lyk<xOu<7!qa=<~K~dAs0@7=*|eT26P(z*E>u#u^U1mZY7x'
        'ib=NmSrGTQ<AEodHk)%%J~Z|0=qNo!Kd_zmvo@PL*_3o_*B-GmS5F0=98O#W-kw}xIAe`yjxk!uFhy#!DES~QaFK}DQa5|Dvwkom'
        'aU#*4VB-jZ%O*#5Xr`VgEgd#akq?J@f*a-$?~SurwNS^Wk`ftXgiQme_BC~QoSbu1H4>wVqpG8SpblGE-5FP{F@4lX1YWG<wQyu8'
        'OR~c;o2mu%>a{k^jTqkUlG8NT)*Rb*OLFo#ozyb_9XJ1D{x=;V1JfJ>JOj+$v{-p!R+(QlF`P(9HjFiFOX{hVl^wlfoPn^Hy(sNl'
        'LI)5nG=9Bee%@D27Lob7oGXU;H^%+4xyL+V9!u|~{mqVoxqQR?N1yr6b@cVNj}-E*Jyst$ucbQaM9<Y(C(4ZSv{T^iZkTsskt{ou'
        'S)Fbn!IKoawl%0W1?kO1!UA#kty=4a5TY_%Wu#-w%5_4qj{$YPP^8-kTlIV`LW3dYH`wUPMi8$YOG)n`EO4dZM$IhLV%tF4MWo>u'
        'Y&}HOQzZ)7!`xVb*-4m?Wss6)FuE$w3RIX+X3X4f?qm~Eamu1&X2*T!RL$|}{S3Uoz=3icD#?*P#8w}98hDCk6kR$80-R{|cF`Fc'
        'js-fJY3M0>SvioUng`9^a2jpZ4|9F=>tm-jjxt><KUs7gtvaV<j`dMgCR$lkD&KeJOW`SnlOd;8L6%0Gw$cHdr{gVel+~{d$DL?m'
        'XfYHKRMKG8VY~h7$?J9;I?GlL+{IU&@{83^`8C{oW}6p1N1C{L)~y|kYx45_P+~N7Z*OJ3%_!2%m}kGlG|WCm2TH?gdZr?lcv`MG'
        'dg(Hu%!^(qKNH^L+5<L)#~hsge(l4&rXE|a^g&<$yM0>sz(D^%S*7%+6;68o5j$_CS5BWkdAd2#Eq(o$wF~`M`p&N@mg{IvWVE;c'
        'E{bwZD!JwCxpUo@E@|hx`+B?AR+K++vN^e}y(F`Dp!?kA{(-NPSnuuLgh6*bl}5%`j%p6op-=Ad4_Gd%R1@ebyR}u<)Lk`aTXf^A'
        'u1%{ci;5+>YsZ6C)#^CWq`AF)SI=JTJ+BeG(#`Zb(_N}TShc0HT0yn)Diu#E<+hbluh|aiWT>w0j2do8l^@TO4QuGrWI(rG=)Ksj'
        'UGDGKE}k9uO846S?>N(>|NF08*7`4Kmy&1CttYm#N&m5&zH}v->>s$iUb>uYQtsw=`q_u&EO}!+sjpV0hSywrlHC&DVc-)6e!##_'
        '82B**KV#sh4E%zDpEK|)27bxFZy5MB1HWV7w+#G&f!{OmCkFn=z+V{nGXwu(;O_+P_dfMvrNegB(u-Bi$NT7Vq|XMs4-%W`Y%gS7'
        'Rxa!HnWx&N`jZ`#%~WJkc+PKp0akx2#;RpfwFaiYRqsD`ff(V{6E;pPqUkoCHvcvW$Zu51VjjK!dL>%DUN_ur>21u?)m&BYq4>QP'
        '0zs_|tlisDlAx6TPsJUx_~{}ui0%}pT0+z{CF$c#y<-e?FwoB5f7UmK<i>+mkxho8Fr4@ws&ly<oiYFb'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
