# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zhangge/worknote/ProtocolV4/uavcan/custom_data_types/dinosaurs/sensor/sonar/Sonar.1.0.uavcan
#
# Generated at:  2025-06-25 01:48:14.758547 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     dinosaurs.sensor.sonar.Sonar
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive
import uavcan.si.sample.length
import uavcan.time

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Sonar_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 timestamp: None | uavcan.time.SynchronizedTimestamp_1_0 = None,
                 name:      None | uavcan.primitive.String_1_0 = None,
                 device_id: None | int | _np_.uint8 = None,
                 sample:    None | uavcan.si.sample.length.Scalar_1_0 = None) -> None:
        """
        dinosaurs.sensor.sonar.Sonar.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param timestamp: uavcan.time.SynchronizedTimestamp.1.0 timestamp
        :param name:      uavcan.primitive.String.1.0 name
        :param device_id: saturated uint8 device_id
        :param sample:    uavcan.si.sample.length.Scalar.1.0 sample
        """
        self._timestamp: uavcan.time.SynchronizedTimestamp_1_0
        self._name:      uavcan.primitive.String_1_0
        self._device_id: int
        self._sample:    uavcan.si.sample.length.Scalar_1_0

        if timestamp is None:
            self.timestamp = uavcan.time.SynchronizedTimestamp_1_0()
        elif isinstance(timestamp, uavcan.time.SynchronizedTimestamp_1_0):
            self.timestamp = timestamp
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 '
                             f'got {type(timestamp).__name__}')

        if name is None:
            self.name = uavcan.primitive.String_1_0()
        elif isinstance(name, uavcan.primitive.String_1_0):
            self.name = name
        else:
            raise ValueError(f'name: expected uavcan.primitive.String_1_0 '
                             f'got {type(name).__name__}')

        self.device_id = device_id if device_id is not None else 0  # type: ignore

        if sample is None:
            self.sample = uavcan.si.sample.length.Scalar_1_0()
        elif isinstance(sample, uavcan.si.sample.length.Scalar_1_0):
            self.sample = sample
        else:
            raise ValueError(f'sample: expected uavcan.si.sample.length.Scalar_1_0 '
                             f'got {type(sample).__name__}')

    @property
    def timestamp(self) -> uavcan.time.SynchronizedTimestamp_1_0:
        """
        uavcan.time.SynchronizedTimestamp.1.0 timestamp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, x: uavcan.time.SynchronizedTimestamp_1_0) -> None:
        if isinstance(x, uavcan.time.SynchronizedTimestamp_1_0):
            self._timestamp = x
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 got {type(x).__name__}')

    @property
    def name(self) -> uavcan.primitive.String_1_0:
        """
        uavcan.primitive.String.1.0 name
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._name

    @name.setter
    def name(self, x: uavcan.primitive.String_1_0) -> None:
        if isinstance(x, uavcan.primitive.String_1_0):
            self._name = x
        else:
            raise ValueError(f'name: expected uavcan.primitive.String_1_0 got {type(x).__name__}')

    @property
    def device_id(self) -> int:
        """
        saturated uint8 device_id
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._device_id

    @device_id.setter
    def device_id(self, x: int | _np_.uint8) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 255:
            self._device_id = x
        else:
            raise ValueError(f'device_id: value {x} is not in [0, 255]')

    @property
    def sample(self) -> uavcan.si.sample.length.Scalar_1_0:
        """
        uavcan.si.sample.length.Scalar.1.0 sample
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._sample

    @sample.setter
    def sample(self, x: uavcan.si.sample.length.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.sample.length.Scalar_1_0):
            self._sample = x
        else:
            raise ValueError(f'sample: expected uavcan.si.sample.length.Scalar_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.timestamp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.name._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.add_aligned_u8(max(min(self.device_id, 255), 0))
        _ser_.pad_to_alignment(8)
        self.sample._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 168 <= (_ser_.current_bit_length - _base_offset_) <= 2216, \
            'Bad serialization of dinosaurs.sensor.sonar.Sonar.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Sonar_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "timestamp"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.time.SynchronizedTimestamp_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "name"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.primitive.String_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "device_id"
        _f2_ = _des_.fetch_aligned_u8()
        # Temporary _f3_ holds the value of "sample"
        _des_.pad_to_alignment(8)
        _f3_ = uavcan.si.sample.length.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = Sonar_1_0(
            timestamp=_f0_,
            name=_f1_,
            device_id=_f2_,
            sample=_f3_)
        _des_.pad_to_alignment(8)
        assert 168 <= (_des_.consumed_bit_length - _base_offset_) <= 2216, \
            'Bad deserialization of dinosaurs.sensor.sonar.Sonar.1.0'
        assert isinstance(self, Sonar_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'timestamp=%s' % self.timestamp,
            'name=%s' % self.name,
            'device_id=%s' % self.device_id,
            'sample=%s' % self.sample,
        ])
        return f'dinosaurs.sensor.sonar.Sonar.1.0({_o_0_})'

    _EXTENT_BYTES_ = 277

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8UR7IY0{`t=O>7iL7M}he8xn?)1ScV+lMomZJTb;5lixK<7CHO!9B&|5Yge10XQptqGt)iWKgMPg$vGr4tCqH<bR<iA;pihr'
        'jvSHp!jU6Kv?q=n_f_}&`iBGpM4Ny_Pj}V(tM|ToRnK}W>JQB~bLqe6rPgxYuQy5+pLw>`urFBE1}jx+ZnNe3cEFP8iPM1>)`HMu'
        'XO>$m`93-PP4ab8jI@elHEDid-F95x3O&E%GskzmlJ7c}S2``8NtCZFGS9bNC*irs_`Lo8eF75XzDvGIq8$}02t2zQ2Fy?XMuN97'
        'sY{ha+9{hg>OE72D|IWdDuJ+%%h@2;qL)K!v1U1?z;3eA>1C(JJ=d`>u=*Jq@B^#aO1Qy?I+pOAq@5Sq?0dGeqvhF6JFpkYjy<0_'
        'zCG`-`bSQ{=9xF>pdFQ}9aI|3nGbjZWwNqn`9Y=W*2&6!(X+E1L4vJxlIBoM3D<m^e40d0SI9=EZh7^7K^Ma+Ep12Bu6eG{YOYgH'
        'BDGR?YsuVy<y`IzXQmT2tIRXqb7mivZwA~7Ol~bQvt{`{tDC;<)R^hJO=emisqids*=*9M6PUI`^eJUf8Wuv^<0RDe?0K3l+9g&x'
        'l2Qo=n^ntahfUiz>+GCOJ~3O&8?{=khF!A)ih0QtVrrr12{~OBp(*s)Fa^r2GSg#!4=Fape$I27J?VZoe5o+ANro}+i0Lzy64hLi'
        '>$hm3wlhzo-l9!wOHHv;?ZdPRGH%gogiKf&xTeDvg`4PcuHl}~?CZ`?9v>x_nCI;}*~w}a+4#=zuxXB(<6lf3AM`AdTU9p<%<=K^'
        'q`Ay2&p%?G=XQ;YsTM^pST30-%;OWO%syVSJ0$FQ=6N@4)JYL(FwM|$SdIC<<=Ktp%mf00X$OAST5=n)k+mWslcY7^Zs-fDR6R}C'
        'LlR+Hq>Ti#C7b-^1cYO==GngOm$Jp2Y!DXg+UUs>GiK3o1M}2}hfP9)L%#G#U(NCe6k$vF>n*doOq*0_Y+1_<*GgkdfucN6N)12L'
        '36<Ft=Fbzc&#gv7L|DLWzQIOQ@=V1!)^k*o(LjdLpc@AQ#i2mJLioTFvknEuBq#c%gf_yHQU0Xsh;0&d_Z{EE_qX3(hBAMJAAp?L'
        'PyA4}b&StuVCIuQ&m{bCbnq|Cb2q9^@kVhI-uTjS&pV|g(krP!N%UeTDX^s$0Zt^dfs~N{G{vXY=-9(2qaj*yO^o_9f2#dX^N}=`'
        '2+RCxSY^?kzC2i|E@#<QtfI)D=g0VHNC~CRNGWY6R!=TQPgc&^ORQcIfvVW`WG32O@!im?F`8(wO3R{j5gFpAVONuAXqGbi(ySQ$'
        'p3;-_CM6E;iWF{KAji(n3-iyr9<5m<+2L8w4cwaB_<VxapQX|ydZ86oX-8K)HXk;GA-&Y=CwwMSh4+$Z|CZ^tbhI>967EX^k>K`J'
        'xaE_XA|X`TTQ<2!VfoKYmI8!mQ-~J$p^V^qlploK1(Io-TeO7(Vex3XNBlmWX%thXgq?s7>^TzPHo`0`q)DNthd#JH&uQ0@pWP;<'
        'yn0))KycM1NtCZTc{$yci$vpkqkfCk>~nS>^6AL<k`Z<aX(+QJ)gjBXQ?BdLw#S~?`ha55-ZYSvz^!<$8>F)QmPMZ8(?$Lf|04(f'
        'F-JbbKjAZ}Th&UnK}b8;L2B>tASVYKzmsU^@9p5@^!qgHZlg%4xUD2Iw-e$oH>)lIfue}4>9*7ICzKDY!1a2EpkAqQN<ax`(XLsm'
        'F0%6`BEBGIXTnB<4xo**eDYsO5z4V&rK?0MlaN3@tkOE0wj&N!da;(oiy;nIf+ev*Ua;k2pN?JHs<gqyo|_4)VzW^e7z%oKfWuKv'
        'B$MvR-*<)B+rC0{cX)|zL&AcM7l*!k!wcKoUp&uRPNKb^Q&txvnafXz(ZPGe6BX8A;;?OBXnNT!PuXmoA6liw57A|UP+$kk3Ff5e'
        'sZMatiJQ?T#sV=OOd0tX+{*k~=ktB;e}?j?NG#5laTMxA7-^>p@bXq)XbKdX0a1HDrDVcBWi1xi+kxWCG-PBsar6tz$7y^*$nizY'
        '<@tFc2Pq3B$n9Sx{Uz_qF{te^tvdz^s4?i-w=CX`fjQ7Xk2~;yp-ppOkQFf8<);z)-mxVe48d>=JF~gG(DlT&bg%<<#_;5TTpFdZ'
        'U3cYyC*a8#3T+)R?EX<|*hN8sr#5M#85-a7llWmbJQc&!8Ldk5I|c7EKbaTyz|%22yQK{@OLKegNftZ<&&Dv)@if`;+&%NdUKokt'
        '`E6|?3Yvf6zU0Dl@O%vW2K+^{B=5!hmIp7uz8Lo3)n1|^nwNf-4tNpv$6$7SE3AI`XG?^az>MLQOpbXs`-S#bABaA98D5FuKu2d^'
        '9E6u%dtf@?RX7mC!5@tbahOC+w1*z3Zg>q2#!&36vmLX;4_pTvf?^D>|KxQN2hqRrQ0#!i@OlhKda*q~GK>B39erqe;SD$vL+PIU'
        'KwQN0=0mj!MxhkLSPuuq3<*acx>k4-#$p)1XO9pk@f~|4_Q6pYk6~gnVvdmPu?}h`ADJz13?^bYeqTN#ZsL9Gk=hEAa6E?cAiBl`'
        'zTST1cEDRy1He1??K_e{{O|rEcEj87P7LpDkHZPlQ5INy{};0l-i7yK_~2*xm!y!4-~FO%fcN2p7^XI1mZBf>3+XWCWX!3U)2YCK'
        'JmzK0t9VDlybc8{$XHOZpu-4`$T*_nh>mv*FwvCJRMFI-h(#HTDi(DZ!!a4hR2<WxjAa?iDwcJa!YLW2RGiXb8mDEPR&iQ~S)7$|'
        'R>fHz=5S8NITh!0IE!axJgeea9jJzvk*mmcXkkmnmWnMMmT*bNB^8%+Siuz;S5#clVHH<pTvc&ZhZtiSV-;f^)^JV6H5J!%xP+Hv'
        'yrkkK9oBJO#&s3fb-0X|WxTB7WgV{I6&bInctwY+cvZ%$Dqhv$8eWs}nu^zSxQ^FlysqMP9d6(a8E>d~Lx-DqQ^uPr-qhh1-jeZ_'
        'innyQjkjgIt>SGR?%*96?~p&qyAtLU%xRc2FfU<V!8|$Hz=DJY1q&J$3>=YgM8OdaM+`J2G!-;8Gz~0DSX8j6VbQ=b3C9#1({Rkd'
        'vV>&?%NmvqoRV-#!6^-=44js5TES@zrwyEya8|)t4QCCUlW<PKISuCwJS*W@1<z`D)<7;HSCDJS4Qxr+Qn00A%fKZGmlRymaLK?G'
        '30D+c(Qw7URS8!WT-9*Zz*xdq!C1rCz%>ci6kOAA&A>|%UQ+OqhL;RnmvCLdbq&`Iye#2m1utuO*}y9jUQzIhhF1){D&bWHuWESJ'
        'z-tm-Q}CLG*9^Qa;dKSCYk1wj8xr17@Q#8vG`wNpO$l!*cvHih2HukJmV&o5yk+2R32!TSTf^H1-jU+4%6w5o7pRCX{67`Zc~Lw)'
        'E}|bn5nagq@VJP62t_nq!87kZ&?4IWv4i;`6w&5j9DcP$wAuT^$8V;H7Hd90l8b}!{Y@9q!Y9QJ5*`=P8;a;b#5^vd@3n}|vP_ZY'
        '3XhBEpHW0-r_$ph`cV|oy^PpjME94_R5xQj->ISHb`7ml;UOw%QADT3wE9by(NsQD9W9D!b?Y)(l+W!-`f(ZkYb~R*8k&mfpIk<_'
        'n+3G2`G+6oUxihRpZGdiC`q{-|JLUxFY*s(_#d|D#fXOb+JbgvZ3BZ1F#L>YcKPQC^RqLj%A?GwxuV&`Pbo!{Rlt^l((viDOHVW='
        'wP$R<*9AlLmT2;-FFRJ#u9<0*f#6L$wT_r}(CK7y!bW2>U|!R9MB7fu{Mi1InX{H(vl?y5rG$Sz(3;Y}0=?b%!1!OcX*}7wwV=^`'
        '`+*0dZ)4!^65TcpexcW!p{A`*nYa78GPdf25S<)#CK`uC2h=8(UL(i;b|Z&xmwc<)YOqq)Fi|>9>$kkSHG=Y|H};Ec(6TQYI@NHk'
        'V4#hI%rx6(M#Gh+HSgF#C^|pij}9H17#lB-ADcLS{8)K%yj-4qyL|NMTVoSP%f}|l6O%`ezdb%VF_ATgWdLk43SC<>696nOoF)V='
        '{7F2%5RWtT2=4|**|#Z*+2ZM?-A+o#OdYTVGWk~<;INGZz3syLM@DaKEhGE42*6g9oG>J%7%KBc`o9T61KlKM?6?0CHb>NRTTpip'
        'xy^hVkexO6`=9@V?_M}5vcT61(;@&LipO{2@zGsE5$&#pe&9Cy+vW(uofc~0-?WK3i8McJpf041)M<R$f#~IqHcb|%yGqfrcI?eD'
        'T38h(U!=!_jnu=S<lT66qo0Op;e9ec3-mOlmg#(VrVE#i;~SffGVWQTnjPTI)NL4FXm$0i)6Du792>?3kV^jp$OOHYcrO3|'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
