# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zhangge/worknote/ProtocolV4/uavcan/custom_data_types/dinosaurs/sensor/ir/MultipleIr.1.0.uavcan
#
# Generated at:  2025-06-25 01:48:14.689737 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     dinosaurs.sensor.ir.MultipleIr
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import dinosaurs.sensor.ir
import uavcan.time

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class MultipleIr_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 timestamp: None | uavcan.time.SynchronizedTimestamp_1_0 = None,
                 ir:        None | _NDArray_[_np_.object_] | list[dinosaurs.sensor.ir.IrData_1_0] = None) -> None:
        """
        dinosaurs.sensor.ir.MultipleIr.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param timestamp: uavcan.time.SynchronizedTimestamp.1.0 timestamp
        :param ir:        dinosaurs.sensor.ir.IrData.1.0[<=16] ir
        """
        self._timestamp: uavcan.time.SynchronizedTimestamp_1_0
        self._ir:        _NDArray_[_np_.object_]

        if timestamp is None:
            self.timestamp = uavcan.time.SynchronizedTimestamp_1_0()
        elif isinstance(timestamp, uavcan.time.SynchronizedTimestamp_1_0):
            self.timestamp = timestamp
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 '
                             f'got {type(timestamp).__name__}')

        if ir is None:
            self.ir = _np_.array([], _np_.object_)
        else:
            if isinstance(ir, _np_.ndarray) and ir.dtype == _np_.object_ and ir.ndim == 1 and ir.size <= 16:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._ir = ir
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                ir = _np_.array(ir, _np_.object_).flatten()
                if not ir.size <= 16:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'ir: invalid array length: not {ir.size} <= 16')
                self._ir = ir
            assert isinstance(self._ir, _np_.ndarray)
            assert self._ir.dtype == _np_.object_  # type: ignore
            assert self._ir.ndim == 1
            assert len(self._ir) <= 16

    @property
    def timestamp(self) -> uavcan.time.SynchronizedTimestamp_1_0:
        """
        uavcan.time.SynchronizedTimestamp.1.0 timestamp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, x: uavcan.time.SynchronizedTimestamp_1_0) -> None:
        if isinstance(x, uavcan.time.SynchronizedTimestamp_1_0):
            self._timestamp = x
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 got {type(x).__name__}')

    @property
    def ir(self) -> _NDArray_[_np_.object_]:
        """
        dinosaurs.sensor.ir.IrData.1.0[<=16] ir
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._ir

    @ir.setter
    def ir(self, x: _NDArray_[_np_.object_] | list[dinosaurs.sensor.ir.IrData_1_0]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.object_ and x.ndim == 1 and x.size <= 16:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._ir = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.object_).flatten()
            if not x.size <= 16:  # Length cannot be checked before casting and flattening
                raise ValueError(f'ir: invalid array length: not {x.size} <= 16')
            self._ir = x
        assert isinstance(self._ir, _np_.ndarray)
        assert self._ir.dtype == _np_.object_  # type: ignore
        assert self._ir.ndim == 1
        assert len(self._ir) <= 16

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.timestamp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
        assert len(self.ir) <= 16, 'self.ir: dinosaurs.sensor.ir.IrData.1.0[<=16]'
        _ser_.add_aligned_u8(len(self.ir))
        for _elem0_ in self.ir:
            _ser_.pad_to_alignment(8)
            _elem0_._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        _ser_.pad_to_alignment(8)
        assert 64 <= (_ser_.current_bit_length - _base_offset_) <= 3648, \
            'Bad serialization of dinosaurs.sensor.ir.MultipleIr.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> MultipleIr_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "timestamp"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.time.SynchronizedTimestamp_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "ir"
        _des_.pad_to_alignment(8)
        # Length field byte-aligned: True; all elements byte-aligned: True.
        _len0_ = _des_.fetch_aligned_u8()
        assert _len0_ >= 0
        if _len0_ > 16:
            raise _des_.FormatError(f'Variable array length prefix {_len0_} > 16')
        _f1_ = _np_.empty(_len0_, _np_.object_)  # type: ignore
        for _i0_ in range(_len0_):
            _des_.pad_to_alignment(8)
            _e0_ = dinosaurs.sensor.ir.IrData_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            _f1_[_i0_] = _e0_
        assert len(_f1_) <= 16, 'dinosaurs.sensor.ir.IrData.1.0[<=16]'
        _des_.pad_to_alignment(8)
        self = MultipleIr_1_0(
            timestamp=_f0_,
            ir=_f1_)
        _des_.pad_to_alignment(8)
        assert 64 <= (_des_.consumed_bit_length - _base_offset_) <= 3648, \
            'Bad deserialization of dinosaurs.sensor.ir.MultipleIr.1.0'
        assert isinstance(self, MultipleIr_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'timestamp=%s' % self.timestamp,
            'ir=%s' % _np_.array2string(self.ir, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
        ])
        return f'dinosaurs.sensor.ir.MultipleIr.1.0({_o_0_})'

    _EXTENT_BYTES_ = 456

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8UR7IY0{^{N&u<(_6&`1uc<k(Y9lRk@b_ulzB{qti*q-suA|Y*XhzPTuScx}8AhuQAU7lA-cUMzYJ@y1v+DL%bq9hhlD<mY2'
        'AkJ_^a7N-k;KZ2|;>Vp=-95jYnII&DCEGn+Rqws}zVCfi^Wpp_zgnpkKjyPpKT=Wb`HD$SWB!B&G4uRTB$-fLGizSCuVo(UT(X0H'
        '#_Th@{?vY8*UVWzr3sE-iFhg$&86}bOO=owm)>3;Yo5jIj<lxk_n1^%q!wys;X(EM%(my+wIAB2)|~gL){+OgX3BmWL(eE`ILn%|'
        'w>gWWQ87z?L^bubs}RnVFX60tGpD_frk>^r^X~W45Tr=?6BZrd3#Dn2Sy+I@K_&1qW`~t(`Rc4XGRYIJc@OJYeJ@qKo3iLms#%xG'
        'Nr=w-0oQ)a(yj*EZef)nRoYKPgjK#_KD|E(<d%86IJW1895g?$_pEu%#~Ra!%4j^$Ngm+V&L=#SLa|V!ku~#vBtrY}uV-qt17IZ0'
        'lYmJg4$0UoMKn-Nfc6;4s8TE<il-qXN+gU>i76zNeUjkER1==!{9>l|mR!*4Jq8t$cX4=)d(69D%yIyefGW05xFQid<cJB$nB1UQ'
        '7W0s5<lG}JOqfgQ;tZF#Ou1r9NE8Vek?cD;a)ZkcrAS86)sVg-7)h`&Ca)94STQLS7*}PuQJ!}3t?Y5!TTu!xvM=E-u(%$LbLOhl'
        'f~2hHV8TC#u{bL08;&=3HV_hW#3QVeg%oT2($W$k8)WPK=FTLtIGqL}*JNv})g*mJrMgazfQR6Qun|(-_sC7M(<ow&t;M=?)Q%)a'
        'B99|Xgc%6Q)0BlwDJpr~FH1ln5U$m*T7(UkVYQBtCT7(ja^+?f>2Wy9F$AHQ4Fj`dj(DXSbxcCZ6<1!lncWz*z{8E*n;o*23Qca`'
        'S|_N46tR?;FQgJhk!KFCw@A>(CUqGz+K&Y-I7Xt-3B024g8@|}apiY$vH}{%j$tRaZp=1{>1B#THUcVP_@dOP9`b;qxTc*f90t;j'
        'rbrAy5S3@K5tdDTSEQ~@^sw(>6|PiIZ?;?TIrx0L=K2Y)m94YzUZ>r;`;Cr;b#wKbOp4Q~3%wz44vojDI7&Th&iO?_)_i7Q3hX#T'
        '!8tRVu!Q=(LZ37q)B{bkh+7WbTZQAdt7jZHb2qH3Oa*zs%<7mA`a!?+SGS8bxD4B{k)xqR43lCzvB;j7W&e;Lv&eTu`8={6bHP_4'
        'mm$M}nE4q+yD$sxU(5q*7WdK9kN4f%XJ}7zUqs^o;Y@tt2?E>gy7G^N#63HcUD}sIi%`T58o2+`O09W4%LD9aU$Sl<yFy0Rt1NWP'
        'yh9I<g{gMyZF)C62cOl>;8uO03d?kc;8!hcPmq>BbxI3xp@|Fa^n;EdB>IDc-6<K{oMH=WSMf&CBWf&X!D5jVwWDF8=P-bX^U@Ux'
        'QyAsJ55T*CU57Y}1T8PB5<3M40wbYc4Sc!i${x-UazkY-<cEAr`FLbJW~iN&g39txO|kOwlp7*iA$D>40maOvf=FKrUkag%SSq84'
        '6nt$B?!ecf4e!Dpbl@&@3Rvg;AV#HK9Vm5lcp%97^k-{c{tDOc7N764VH=s3e34m0W(86GBoHVBWO0urqO#??=m%5_IXVQ-`5~YI'
        'SzzYXeHuA;er^&xa-*F*j`09GJqpbq+qHJ<V-?_4A}b@<c0CVpp9xRh!HN&`*gY(`!xd$T%i49ftoE_OV;5T$8{G9=Cl6e+p$jbP'
        '(H&sj)SQ`&PX5<t+(4wHeQPc~KwoxmO3-e)x05ITD?W>vJ1(EQl3bp4UAiN0p#WcW7lEhM)Az@`t&ZNd1=l`8C>HT*ftujDZ`&*8'
        'Qv;?B-8HGIVRGHoVja8>v;;YV?id#r(Nvwwq*F<C*&L_Xwob{Ajqy}Ro+d(Fx`)of?y-z%K1(5wOa4}H!Rc67W8Q&Y`$IUwx$U`<'
        ')B(9UJV8d8swRE(f=Lza^M$LzI(%=O@G*j}RCh+jJ%!>x+Dk0G`yoYnzL2EXPV4GamN(4eZ9FyggjkReQW1$#O=uVIE4jNNe%V~x'
        'Zrs>vZEZJpcD7s1tyZh~c58F<ts9Na)^?-SXm0Mjz13_q%0r~s-r0oVt)R-x;HHcJd-xsv5&n?F?g`xLz*nc(hB>1+dVINIe5kIP'
        '=GAi3leP^9CoVobm~gQf5zbYxG5FRDyPB@Sc=$AW_w#bvFC6I8W&-H;oD&S5`aS$T8gqd{0~6{ZsIEde?T0w~;gs3hxy<bGN>PJ7'
        'PhkEV_!0aKeme_ub0N%?7RmV8X%>gp;D9X50b%9%=R#=^1q~J6Ln6!qm&N&IOG0KxIak@t6e|7>|M=fh@v{MV!?rwy?VpED`<L0s'
        '&loO%{|VZ~PyY*38?X2UhV{$p>DSJU9=$YIs}&NcL2s|N{Cp{;fa*9}U!JKDhyH{*z6%!~eE~zm2Q!-z8G(Pozs$waSLx~W7s3An'
        '^Gjpj$NwMf!?1ORjacCE=rV4)gzO!J?49M|$Z)}__YOht-$CFbtg#RP00'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
