# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-06-25 01:48:14.768361 UTC
# Namespace:     dinosaurs.sensor.batterystatus

from dinosaurs.sensor.batterystatus.BatteryStatus_1_0 import BatteryStatus_1_0 as BatteryStatus_1_0
from dinosaurs.sensor.batterystatus.ErrorCode_1_0 import ErrorCode_1_0 as ErrorCode_1_0
from dinosaurs.sensor.batterystatus.Parameter_1_0 import Parameter_1_0 as Parameter_1_0
from dinosaurs.sensor.batterystatus.Statu_1_0 import Statu_1_0 as Statu_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
BatteryStatus_1 = BatteryStatus_1_0
ErrorCode_1 = ErrorCode_1_0
Parameter_1 = Parameter_1_0
Statu_1 = Statu_1_0
