# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-06-25 01:48:13.252615 UTC
# Namespace:     uavcan.metatransport.udp

from uavcan.metatransport.udp.Endpoint_0_1 import Endpoint_0_1 as Endpoint_0_1
from uavcan.metatransport.udp.Frame_0_1 import Frame_0_1 as Frame_0_1

# Convenience aliases of the newest minor versions known at the time of code generation.
Endpoint_0 = Endpoint_0_1
Frame_0 = Frame_0_1
