# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zhangge/worknote/ProtocolV4/uavcan/custom_data_types/dinosaurs/sensor/scanner/Scanner.1.0.uavcan
#
# Generated at:  2025-06-25 01:48:14.736918 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     dinosaurs.sensor.scanner.Scanner
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive
import uavcan.time

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Scanner_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 timestamp:    None | uavcan.time.SynchronizedTimestamp_1_0 = None,
                 name:         None | uavcan.primitive.String_1_0 = None,
                 button_state: None | bool = None,
                 magnet_state: None | bool = None) -> None:
        """
        dinosaurs.sensor.scanner.Scanner.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param timestamp:    uavcan.time.SynchronizedTimestamp.1.0 timestamp
        :param name:         uavcan.primitive.String.1.0 name
        :param button_state: saturated bool button_state
        :param magnet_state: saturated bool magnet_state
        """
        self._timestamp:    uavcan.time.SynchronizedTimestamp_1_0
        self._name:         uavcan.primitive.String_1_0
        self._button_state: bool
        self._magnet_state: bool

        if timestamp is None:
            self.timestamp = uavcan.time.SynchronizedTimestamp_1_0()
        elif isinstance(timestamp, uavcan.time.SynchronizedTimestamp_1_0):
            self.timestamp = timestamp
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 '
                             f'got {type(timestamp).__name__}')

        if name is None:
            self.name = uavcan.primitive.String_1_0()
        elif isinstance(name, uavcan.primitive.String_1_0):
            self.name = name
        else:
            raise ValueError(f'name: expected uavcan.primitive.String_1_0 '
                             f'got {type(name).__name__}')

        self.button_state = button_state if button_state is not None else False

        self.magnet_state = magnet_state if magnet_state is not None else False

    @property
    def timestamp(self) -> uavcan.time.SynchronizedTimestamp_1_0:
        """
        uavcan.time.SynchronizedTimestamp.1.0 timestamp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, x: uavcan.time.SynchronizedTimestamp_1_0) -> None:
        if isinstance(x, uavcan.time.SynchronizedTimestamp_1_0):
            self._timestamp = x
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 got {type(x).__name__}')

    @property
    def name(self) -> uavcan.primitive.String_1_0:
        """
        uavcan.primitive.String.1.0 name
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._name

    @name.setter
    def name(self, x: uavcan.primitive.String_1_0) -> None:
        if isinstance(x, uavcan.primitive.String_1_0):
            self._name = x
        else:
            raise ValueError(f'name: expected uavcan.primitive.String_1_0 got {type(x).__name__}')

    @property
    def button_state(self) -> bool:
        """
        saturated bool button_state
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._button_state

    @button_state.setter
    def button_state(self, x: bool) -> None:
        self._button_state = bool(x)  # Cast to bool implements saturation

    @property
    def magnet_state(self) -> bool:
        """
        saturated bool magnet_state
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._magnet_state

    @magnet_state.setter
    def magnet_state(self, x: bool) -> None:
        self._magnet_state = bool(x)  # Cast to bool implements saturation

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.timestamp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.name._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.add_unaligned_bit(self.button_state)
        _ser_.add_unaligned_bit(self.magnet_state)
        _ser_.pad_to_alignment(8)
        assert 80 <= (_ser_.current_bit_length - _base_offset_) <= 2128, \
            'Bad serialization of dinosaurs.sensor.scanner.Scanner.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Scanner_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "timestamp"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.time.SynchronizedTimestamp_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "name"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.primitive.String_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "button_state"
        _f2_ = _des_.fetch_unaligned_bit()
        # Temporary _f3_ holds the value of "magnet_state"
        _f3_ = _des_.fetch_unaligned_bit()
        self = Scanner_1_0(
            timestamp=_f0_,
            name=_f1_,
            button_state=_f2_,
            magnet_state=_f3_)
        _des_.pad_to_alignment(8)
        assert 80 <= (_des_.consumed_bit_length - _base_offset_) <= 2128, \
            'Bad deserialization of dinosaurs.sensor.scanner.Scanner.1.0'
        assert isinstance(self, Scanner_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'timestamp=%s' % self.timestamp,
            'name=%s' % self.name,
            'button_state=%s' % self.button_state,
            'magnet_state=%s' % self.magnet_state,
        ])
        return f'dinosaurs.sensor.scanner.Scanner.1.0({_o_0_})'

    _EXTENT_BYTES_ = 266

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8UR7IY0{`t=O>7ib5}y7ao4)}<Z~{r1gusyCi9>)mf4e4RSwp3a7YJ+ZYBTiAJp3AFx@Y^x*z87f4q2I1OWRU9lBK<H^pPV+'
        'j+XYqkt0X6CypGqUibWBJN$z-!IEdX->aYRRn@EaYE<*;PyTQ&{fpje&ei-{y;Sy@XIpjqvQ??GQn~6jnyzmLEQvOp4!p1$gdRIH'
        '*JR0$$-eKC?~-Dql^v@=^JdL<T;B>kzvMH=cfFEdwH$|erPJAW66MP?%=2y6Nq8<Y&bFR^OhAI%Ka%g0XkFO~0?)350rQi;knlBN'
        'b*Pd^J7%+btqW(cT(bhJ90-hD&IY*_?Fy|Kf>8?W1}mMObE@2P9s4q?ouL6guo}&T8+@RRgs&&<ywGCbx)zS6XE*G?o*^7tzj1tf'
        '+F`ZhPQa#_*KeeC<%%7Y>&%%Bcmkt@vTFH3x#89b<<98U$+jTDRys;^D5ivIen?Iw(JN)b=+rE))+^{rSfQn@YuHuK^;y+*YDuJ)'
        'Yi>1}`mdbJo#D)M!bXL8rhDG(q4LduTY<@~8D=&u-)A+`x1B08eYe3(%Oe$@<;|H5dUXQRc8ETu3`&DSXltB=x}H5v(?z?)O8ZkP'
        'VPLaj`D~wQ`(}-ux5*}ElX=5dvst&RRzN;4nL<o8^gJP_!y+_=J{u%QnH6Sw?5`pDhS<-0Zlf#R@3=1&W;O^I^Y)uQV<}P9CAof+'
        '7HT`wH0sURw6+wAooXMXRS>uts~$3eGH^|Y%?LBm$N9Q@DZ|&9KXiDQOk!TLYlM?kEyDQe;Gk&^n+Lu<bhzKLL~d2wFfb1s7(Hap'
        'G0XG!o0qs<<zlKyo(twm<`MJo!Bl1sFX0X;c0BWv8`f*2h%}gHNL#1MeBbiy`dkKq0>QKczk`;{Mr?#uc;pai4Y(Wnf+|%{)3uO9'
        'm=<Xx!EDwhdpQBcv03$O-}Xz{Vvg1+7VPTq(IXRP(QyOw*jM{ZiUfyj>5;yw<xx<CO<}K(&B`2YQlYVF&DC8i^)We$azQBtex~gz'
        'vmxM56S2>&dR=%}gxhqT4X5Opiu0^%s0O2fEJlNlA1EmH1|lqk4LmXHkYh|TqF+jABW#TFM_os3lc2Nj_*VXA>uDE^^0)bJ$cg>L'
        '_hwti_+|noPX2Ks;rpUJe`20{zv?vJ$Zx_L7ajMKQ%WMeoB~RsH`+;o%{D3EL^A733HeiLd|LH39)2hqpe0wus8939TF*2eNh66s'
        '=2yZBi?;UU!E$9T%dlb<MgBVfh!2O9P-={n(sp9C<Vv)$eBPdAwX$$j*{&rM(dM%6hF+D?M4gqJ7Nv{G5MOn>l0*ZOl+|Y^#psWe'
        'o}>>bad20papN)>c6wUCzvOzfW|3qECp|ZCt8V@5L0W&7N|R_uGpx{#E_-Y`tP3FB)axgFB2tC*lIYD<({1U)(nv{|F9}3~+gj$9'
        'PcTJ7D7Ut3a)sRTpNT952+^hxE#ikVg6mO!5M~#VOxxU|EgT5M!|5LJdvvB=OqEjX1iWw0kpQ<IW?3Ok3SB+)!tH5JyN>MaHYnxQ'
        'T8c#kS6q@r`Kq0l(_J}3G_E)7H(Av_Z}&t#9T^uH#ZDo0Wp=DOggiUtIu>nNY}@Jw6pOZ}jw}am*>l|>mE|`rvJ@XL^5gsj2mUoj'
        'KEY4&iPWrWxl*S{+tZHJ?%_d34(@+XqV-?e!Pn{gY1Y|Bky3V>bil7A#Gh+aTnYs8BC>|tO3NoHA6S9wbq_(kT;-I263(JclU7Y+'
        '=M_Z!f|#8M>vcMS?w{p{{*@GAH1;cWm1t%X63B-YT4%#{#KB4r)~t9i#NkR|No<f8Y`NH{W0$rnZE&&YCc=u?Y?K8Cg6<t)Uz8Kc'
        'q;vB3Tp_l%t`MCaUZNY3Kyd%Xq37PPV~zWZ=UH<}wEZk)bup5e{D>Iszc*|svpN%pZR<kQ&1QMZW(WA*1zP+7T_z|B>|idzoD^+o'
        'JLkN(8LeO}5aXVdk$=mr%&s*)-DCc3lt)EkaaQ%CP$%3-J5>ZPZ}zyRK(6T%wfz(&6LyL<Szxaf6c<yM5pv?_6_$@v|Adg^GnmWs'
        'OGFM*=1P!T-%9#T)|X>YTVq;h3=~jf(6e`0JR5y;pn)E@!vh9Z%z;5DV6ekaBlNy*RXP}e!5G$Ob9td_!<uxk4%Wx8u}?0I(%7b-'
        '<$(>bF@{1*M+}=ENDZ6FDX?XQCYqt~tq;Wyn_)`~uVl0;&94`{+a8)1w!$khyt*m|nx(nzk0cAW!K*P0wJl9pUVCJI*bYN6yuKzT'
        'qM-R5k0lpggV$r&*=H}BC3$Z=wmjGYJ7akBXYmph(Y*CUI^Yd>GX}F`TY-Al6HA1*z>MMTOpf_;_=Wa&o{B!$1#ic&yREaw55h|C'
        'J~bWi4(yI$&jUR}941i{?cS%V8{UOIF%;YDZ24^8Q`Z4|p%}w^54}#}Ao};82@co?@5Qjc>)YKVv)Jq3;b*27-iQ4$lpe_r#6>(G'
        'JX1_C45b)Gx^Ym<BH_blt`$Cjkr)m<vPFoK_&$0r_~1i05W~Th5wo9UkF=xa&~w8AAHl&G4nLO7h?{sney&*I5FCzSv_HB=M0|bn'
        '+;PCiR0F`Lk8L}WK>VM*5Zv$yd>X^&YscY1(lIJx@rxIR4?cs>WBAPz*_Wh{jNiV{HNY3}n;6Dc#4LF~<d@T7%*mKjF{e|30eQ^J'
        'm{;+hhIt(dSdg)xVnK%?9FlQJ#UUN<8DOF*qp6~)LlKKI7F8_jFoGj8j;J`I!zhl*II7~P4r4eb<CuzLI*jAEjN>Yf>oAFvGES;E'
        'slyab$vCCrln&?coQ&sGJf{QI@G^20xeiTi%Ggw~slzPJ$~ddytPb-yFXOz5^Excxf{Y6)F6a<rEMu%<tivKM%DAZFq7GN_s*G1v'
        'ysE<zF3Gs0;*t*6@S2R*RJ^9cb-XU)brrAca0741ctgb-IxOR|jLRx6>u?iq%6L=7n>yUWTQc5K@s<v^@wSY&RlKdk9lRss9To5B'
        'a2M~&cvr={I^4s1GTtM5l657_DVWnRXJB5!yn=Z$vVjE&3knuAEEqT>;gEtu8V(s~N@yx*YG@i*l(48^QNyBvBNC1%IHKW*fuj<R'
        'Dmbd)sDWb=jwv{%;h2Hr5{@f4uHm?WlM+rUIH}>Jfm0GrDLAF!l!50YJg49}4bK_KCFBZn4Y`3$37ZNwHEbF<E8(nyvl`ACI4|M6'
        'g7X^A8@M3hf`SVgE*Ka~7%LcS7#p}K;i7_z8ZH`mRl=(ZUe)lbflCrDDY&HJl7ZJGyr$qa4X+t^UBc@MUf1xtfj1<)q2LV-Zy2~N'
        ';j)6u8ZH}nQ^K1H-qi4>fwv^QrQkgUZ)teTz}phuR`9llw+*}_;T;9<Xn4oKyAs}2@UDh;4ZJ7CVTJjkh%QhOUHE@0qVuA7dRat2'
        'ha$R=+2Lgo{S1m|x`JoceX2#Y`JjXO85GfGzaM_FMYP%d;p10RM2j`=CdtKq|Ng3rXkn9LI}%<N(f1Y6{SouBh<?-}I?FOenk&34'
        'qMx9M&Q7J5MfCG1qPrQfw}|d7p{Z`he7;>n%dHw(r@}*2(xQk?i)r;mmeEu`QyndeX?687T9nVNO8R9P{Yx#Qvl^O;>4z?(Tg?Jm'
        '*8Icw@xO-^iy!$exlodFIsSvsk6z(lP4M5X(u)xd^t1(S%Gw6{8({bu(d_ciBjz_}j*Sj8r|ODk6F;RCO;!P$4N8Nj(=I*HnADoF'
        '{caZw(OaU)t2XCY4ZCWlO$LHD?bO<D+CjUM$qDQA;edG!+YxO$CG%_hA~Po~ziQQ6l1m9c+t-@Xy8^w{_`vv|*JwOhy|tj;dHRV5'
        'qHm+`cZp7$2EW|x%}~?Ur_9<tT^T#0bziz}omoy_zXaa}Qq~ud^>?kWghAjsqIoh{DdocN$#H8iHmqrf1$~T6IJ?OI#y4L$Dm?z('
        'g%k93;VbcRQhWe?glj}Ww7DAkf!pY9k%|U7Ewg0PtZ6oh48PqjyQS4Qn?_2@58YVl&}EK#fGnfkguBvb7ycl?pQ4Y4@mzOoF(do8'
        'Xaad&l)Mu+qkM+`DQwbcx$p(S&wl6{r+^yIcV>t|3RfHNZ8ec%zx6ZOaiTiD3itivt8<?qsuO+O8Q4i0pX`o{*e?AK0L`nDek}k1'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
