# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zhangge/worknote/ProtocolV4/uavcan/custom_data_types/dinosaurs/actuator/ordinary_motor/Query.1.0.uavcan
#
# Generated at:  2025-06-25 01:48:14.859595 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     dinosaurs.actuator.ordinary_motor.Query
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Query_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     motor_id: None | int | _np_.uint32 = None) -> None:
            """
            dinosaurs.actuator.ordinary_motor.Query.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param motor_id: saturated uint32 motor_id
            """
            self._motor_id: int

            self.motor_id = motor_id if motor_id is not None else 0  # type: ignore

        @property
        def motor_id(self) -> int:
            """
            saturated uint32 motor_id
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._motor_id

        @motor_id.setter
        def motor_id(self, x: int | _np_.uint32) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 4294967295:
                self._motor_id = x
            else:
                raise ValueError(f'motor_id: value {x} is not in [0, 4294967295]')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u32(max(min(self.motor_id, 4294967295), 0))
            _ser_.pad_to_alignment(8)
            assert 32 <= (_ser_.current_bit_length - _base_offset_) <= 32, \
                'Bad serialization of dinosaurs.actuator.ordinary_motor.Query.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> Query_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "motor_id"
            _f0_ = _des_.fetch_aligned_u32()
            self = Query_1_0.Request(
                motor_id=_f0_)
            _des_.pad_to_alignment(8)
            assert 32 <= (_des_.consumed_bit_length - _base_offset_) <= 32, \
                'Bad deserialization of dinosaurs.actuator.ordinary_motor.Query.Request.1.0'
            assert isinstance(self, Query_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'motor_id=%s' % self.motor_id,
            ])
            return f'dinosaurs.actuator.ordinary_motor.Query.Request.1.0({_o_0_})'

        _EXTENT_BYTES_ = 16

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8UR7IY0{^8{U2hXd6m>)rn}m-<p+Qw8aHSR*s5U^;PpMQY6%txvjQMy$Fq+-H^&PRES!QP47%5VC0D&}8BW3#DpV~XSHgNz;'
            'mAWrGvv=;9d(Sy{_ZR=(UT##6yI71fljRXJpasvxOP=Hqu~ZEUWrPLqPX7+M7}7F(I4-~+`pd8Up6|G2CZq)IvEfcXu)0ibsp0sM'
            'B_{chAht3gmEol}5vOC^Djg|JAGsd0p$gmkCFpU~hZiLn>s^bDKpUZCfNwsYtPg#>5I5fVSKh5MZmkwcX~FoXeqJB%4|%tATR@&2'
            '6}Q4NZaK4|;(6(X4xNh;o!EFJjTlJC?nny*(8oJnWr?sX2RX3l<2He(+*s-@1CO7(&E6C!q(!$Vwi80sP~)}ldv}f*%VoxOHVgE&'
            'OmM}uDu$TIyjx_MO1*3NGU0Axh60w1Yp(Y^evO-k3d*3+kaE(^zjJ5UA7U3WRw!))QrE3Bqe`6u1#(~or|VoZymFCvcd|$7@Aksi'
            'Luzkfi|$4hv~0daE(Zfzwf<E4xm1DMm7b;=Q<Xp7_HMc4qm)bU*3;5hH9X?k5b%2|5Wv(7-kmva2k+KuLtKxpMH4t1c-mmd4OOc_'
            '+Mv})q~PD;CAYd0^4c##7G+mt)Gn5EG+3nbpYL9}U!ydqb_936Vu)GAv{JT0HwCA=ajS#Z@H*bWZ*d#H!|(Bjs?bH2<aEuYsjrSy'
            'rLygZd+$#DChXm6|A4j=U%3-Z72dVyftc|yQMn*TZ0x{Lk!vlD$-M$})!EFbrYOk!*mGxlJfm(0A05I+A=)kToS679N(dvKm*D^M'
            'ow$8q5*pB=2J&&MOsL(Vkiq!0;Jabb4CXI$9<o;$>=s;BGu$l`lLTMmDxShMTz~3ulVfLMT)grQuXgd9Pw<LA;!pT<U>AQO$?+!s'
            '`u|kL+w;_GQo)vd<Kum|Nt0Cn05wD48NI5127WOi?n2zgi}+={5GEPF3PXDb?^Z#)hy59PKf9%5m`M3ao!rS<Ch~T$D?X_qo=rJF'
            '26etqQwV)1z>0aIKd-e|ql8(k)<Goz?_v_~W4cEQhR=-ygFxzlnZ*A2I2ID4e*uz`kOn^n000'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     current_gear: None | int | _np_.uint8 = None,
                     target_gear:  None | int | _np_.uint8 = None) -> None:
            """
            dinosaurs.actuator.ordinary_motor.Query.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param current_gear: saturated uint8 current_gear
            :param target_gear:  saturated uint8 target_gear
            """
            self._current_gear: int
            self._target_gear:  int

            self.current_gear = current_gear if current_gear is not None else 0  # type: ignore

            self.target_gear = target_gear if target_gear is not None else 0  # type: ignore

        @property
        def current_gear(self) -> int:
            """
            saturated uint8 current_gear
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._current_gear

        @current_gear.setter
        def current_gear(self, x: int | _np_.uint8) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 255:
                self._current_gear = x
            else:
                raise ValueError(f'current_gear: value {x} is not in [0, 255]')

        @property
        def target_gear(self) -> int:
            """
            saturated uint8 target_gear
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._target_gear

        @target_gear.setter
        def target_gear(self, x: int | _np_.uint8) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 255:
                self._target_gear = x
            else:
                raise ValueError(f'target_gear: value {x} is not in [0, 255]')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u8(max(min(self.current_gear, 255), 0))
            _ser_.add_aligned_u8(max(min(self.target_gear, 255), 0))
            _ser_.pad_to_alignment(8)
            assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 16, \
                'Bad serialization of dinosaurs.actuator.ordinary_motor.Query.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> Query_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f1_ holds the value of "current_gear"
            _f1_ = _des_.fetch_aligned_u8()
            # Temporary _f2_ holds the value of "target_gear"
            _f2_ = _des_.fetch_aligned_u8()
            self = Query_1_0.Response(
                current_gear=_f1_,
                target_gear=_f2_)
            _des_.pad_to_alignment(8)
            assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 16, \
                'Bad deserialization of dinosaurs.actuator.ordinary_motor.Query.Response.1.0'
            assert isinstance(self, Query_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'current_gear=%s' % self.current_gear,
                'target_gear=%s' % self.target_gear,
            ])
            return f'dinosaurs.actuator.ordinary_motor.Query.Response.1.0({_o_0_})'

        _EXTENT_BYTES_ = 16

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8UR7IY0{^8|ZEG7x5SFQJ$uCK4+&C?T`byiNLQs{`_a<$rQ$tars7hlBB`kY)W6hG&?sa!hmI4LmLrVe+4S4&#Kee-WvMt9E'
            '1S$~Pmzig0o_S_;wD`|Xy;gqQPCiLZnzfh#EqErL@Hm4OOVlt|Mp*Ff(jCaeke2B$lN|i9|LCdz!#CYB6H<cqSaX*iSY0Hx&~V;l'
            'iAg>rh;}NZGQ7~H#mS6YrCUnVA=eW&RAKvb0eaHvgUOXN<kDax&_*a3@ay~2^|9|PbZUS3r{1kGZmkw^VZr!E^w^wCPOZFK+7pna'
            'XW^}~lv~bhh<ToSu0!r(L>5~Qr4a)O=}*$a0QC7>*H|np%Rmk+`c8wu6K*VJmx9N)-FEK;D7dwD>F!>*qKs;P`o4E>GGn<+xlU(+'
            'o)s~!y7i>c8l+_d;M%)Ima4?NTZafTvIvoe-wQBQp{OJ?N)?z$DjUIA7<(g{b&qaG?eX58C*Z49==c`CGhMygY2XgNj~`U;u34@J'
            'Fnt!UyOk6Uc#+wtP43{fW=g=~Nmc9s^C52I4Qv)fN(#A#gi~z(xx35`#28YRD{Yxbeb;R=qY9k>U1Y#=PAR*3_{l`<-Aa!%IPQhh'
            'W1@KBW6B*>P*nX1ayb|Tp&Tmxm~y4%YEM)8iOTjr^=`S~ql8QEHj~0wH9V`eA>dO%62OThy}Nu~l-_Mrvb@=9x2AA5)M|?%HxzA2'
            'D(Ph;67bK6pc=W9G*k^F>An)@>pr+tK1epFodE7y$qTcJX{BrlZ*opA;%80#9KXOX@hkiqzrkC0y9{rU#TmVG{Y24cdZJ+M%X{zE'
            'e-QR=xqm?0siNH*Oy%B1^FYjG7^_T>4!7>XP*J~F>d^Z+=rXmLF_EC4uETwIrN>iBcW}W7f5Tr-SNrbju987A@|BQor9vd~1GO`r'
            'k7h8gbc-w_VlQ|vvk}h<@PGSer}4tXG->iGESfDvOymuP3=K>RJ`Rg|XyPK{!F!d#IOnn)MqTQWVF`-)2^yFfO=klweG9rc3`V-s'
            'C@vnGIP@5<;W}>MX2@h4n}Ds^2Ez7pyxGN1UQucM7Qe&qL%ngAq=$F#$NwobygN@&b;_E`VSVSwZBt8E{|A~O@RWYa0Xj27BAOxZ'
            'br!-{t0u{P>{mQJoT*k)9UX+sXK9Rx#&dGG)~8m7KICA<JdHiBinT!wFP9`x-zDac0`r|lIIg`gWeLh^g}Z+*-UY|jf2*XClPU)Q'
            '00'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    def __repr__(self) -> str:
        return 'dinosaurs.actuator.ordinary_motor.Query.1.0()'


    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8UR7IY0{_ic>uVfU6yIRd-8|YP#HL_T2b8+Cb(2DUw+c-O$eJ~eK0qwjJ2N+P#?H>2-g_t6Ee2Ad(!do1xqk42RFHn~?~{rj'
        'J$GjIk;k^N`oV=|@7#ON@0|NPzjJ1{hkqIyFJ&M7deZi#AJvFtBBW7xpSlsN5sx<$E<?qP9$#Z(BlOsfcEZe_Isd?HnW{cX1iP0q'
        'sfe=sP|_!_vnXt$i@)FU1PSAqiOgh8iPTf6H~=<6V%o$|bAA|eNmC(f6wRpOqQ(VoQqd+&ZXZ`tCfc>tJhsslvcZH5d2Hd!w~F<i'
        'sSnjl-<t=RJ)ug8&`lMS=8hS3->#9-Ba0!6{9bZn#HWhp*Bs=Y2z&Ez11)B5#xe|I=6@C|7BI2@rsKp76^U3JC@^&g!99u`Ho1=+'
        'zNTlFJ3!X0wt#0#_6RRjdT3USewj!`W1kAYALvo)!lbTb43W?`dYJg!GrD9_m+F~53W(dzx!yAHHk_51kk1mqJc@NQJNgt^4_nM9'
        '2^Y#DHS{!*JQW_pgNTuYVmMv4KT+r!J-Uo4X)W8`J-pt~9L5H2YgxVzG!6n>RW`Y}8*|I;*s{PJJs#b<Z1jngZg?~{dfH2+;>{k<'
        '5`nu?K!A=Ij6Str4n|Mqg1A(huN830@-#z$O3YTUSlL=x0h>o~L60w4Kj)tHLhp=>T<tNMT8UJT9eZRYM=5vY$n=?vA)+`DoU067'
        'CKO}C<tn@j@4@@<0elD_!N+hVOLUmH5r#R}(N(Xin6^6jZ1lvnP<@^~ui;~%EBzATiP6p=5ZP|JJPJ_}GfS+=QMC%&<coxf>}Gwf'
        '>OqLwhnsqGnfiF!;E)k~X-^wz6d@A_PZ42*MkzBtnrhwIl`b}Dk^`A~C3W$-%`mpY#|3TKMcIl!ji~h=BdnFsIP2j?>Ppw@8m3?x'
        'PQ&aS17|6`QwSI4c3{2%myX~SuEHnqsbv?gVaZ_uuK&BLLVZy6%9yZ1-I)5ep2bee2cRIpsE<GSXmkqV-l#k9CY-Ae*-nP@wrLx%'
        'k{!YgxZOwZ=>;C!j*O42lOD~>gxa=pg|Bl6ufzF1s57hBg>022OofAremAeh6gu={Rd%xitT!O2Zv$*$1?_feSHd?~9VUyjUk{&I'
        'N1P=B#m{5O3L?ryUSlv(tS0sR@kf4+Wjbo8!Yc*Jt9=w#km71i?xddZQjtx7fKhw_UC>uHfyIsj<`i!)<~vys$LCBsIHVlb3Z=T}'
        '^m{s2o%z<{A`a8%ha6W_1gsZv)Mx87jg&Kw?##-!3ctZ)_#K|4|3JeRUrfW5E^C8De6$F^>aKcw-{ocxE%!%R9uyC-`j8b6G8Et!'
        'Rg#J0kX@!ElwW|~t`W2I;?Q<65`O84;4wV;f6}^%P18Ei{NFyK?fcn%Moa%ttaktFens)Vb<AcwvIi>&P%hfaSZ?>V%g^=?is<%m'
        'c3jl$Df|I{!Jo&i+s+G*^ufhS-P+%*0rT$_3jhE'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
