# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-06-25 01:48:13.222745 UTC
# Namespace:     uavcan.metatransport.serial

from uavcan.metatransport.serial.Fragment_0_2 import Fragment_0_2 as Fragment_0_2
from uavcan.metatransport.serial.Fragment_0_1 import Fragment_0_1 as Fragment_0_1

# Convenience aliases of the newest minor versions known at the time of code generation.
Fragment_0 = Fragment_0_2
