# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zhangge/worknote/ProtocolV4/uavcan/custom_data_types/dinosaurs/actuator/motion_controller/RobotMotionSoftEmergencyStop.1.0.uavcan
#
# Generated at:  2025-06-25 01:48:14.907104 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     dinosaurs.actuator.motion_controller.RobotMotionSoftEmergencyStop
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class RobotMotionSoftEmergencyStop_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 state: None | bool = None) -> None:
        """
        dinosaurs.actuator.motion_controller.RobotMotionSoftEmergencyStop.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param state: saturated bool state
        """
        self._state: bool

        self.state = state if state is not None else False

    @property
    def state(self) -> bool:
        """
        saturated bool state
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._state

    @state.setter
    def state(self, x: bool) -> None:
        self._state = bool(x)  # Cast to bool implements saturation

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.add_unaligned_bit(self.state)
        _ser_.skip_bits(7)
        _ser_.pad_to_alignment(8)
        assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 8, \
            'Bad serialization of dinosaurs.actuator.motion_controller.RobotMotionSoftEmergencyStop.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> RobotMotionSoftEmergencyStop_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "state"
        _f0_ = _des_.fetch_unaligned_bit()
        # Temporary _f1_ holds the value of ""
        _des_.skip_bits(7)
        self = RobotMotionSoftEmergencyStop_1_0(
            state=_f0_)
        _des_.pad_to_alignment(8)
        assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 8, \
            'Bad deserialization of dinosaurs.actuator.motion_controller.RobotMotionSoftEmergencyStop.1.0'
        assert isinstance(self, RobotMotionSoftEmergencyStop_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'state=%s' % self.state,
        ])
        return f'dinosaurs.actuator.motion_controller.RobotMotionSoftEmergencyStop.1.0({_o_0_})'

    _EXTENT_BYTES_ = 1

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8UR7IY0{@j%ZEF-U5WZrs*Eg%BRZ#@5{h;;Bs#xDY*`i<0)}yCI1PR&Q^b*Zx)+Br06$C3N6aos3|JTW0uf5tAaADabGxN+m'
        'lV|qZ=%4S^O8K}Oc`r4ojEG@cP${-)ELlVn$Z{~kGVji}tS%B;X!fR;Gr#9=@A$8N$yJG>8QPzxLV=-$HW5WPYC%UCSOE%Al+_?5'
        ')6oXRVAsmy7HruU8Pjd1l3vR~?%g=)Fm2H0dBxQ>_t$&AG192~^gG^75o)a#abcP9A29nVbsu<nSA8j%Ob_dwBq_C&*g)d6@LY>b'
        'SkXa`sTBaps5(k|ip0Va$yD2NtPVjFYAnehWuDKw%gq5m2#Z$HwiZmtr1HaWcsEasr7ER59R}JhVqSGsG=;)PNeYQ~6_2MgZn{ZR'
        '>~Q-i8$Rc*olKzvBE^Po;%B&Yezj3En1wI$1-@9s%*_q8l*GOMZK7kH&l=>JvRtzS3rhX2n;~1G%TkhqwgmCl-7GOs=!Bs`GLlnd'
        ';cDR{MeN-~6UEbQhSNRl+Q=Pb#UZGrw#}((w{bQ81@tEcf$?NhgM|d-=CXHV1??nMc{iIB#zJ;@Z3cl4#D)L^xuNSZ!FhM<EXhUp'
        'qPx+4A{#Ddj&N#_hi1x#j&?-C{4QT`bsb>p{RDM`Ky@}is+&^17t7xDXGURsU!ng|>h&|HgSjhZgNX&A0c@Gg<P;0!_m}uGf50E|'
        'NBl8=!k_YIC7V$aOH6xnAdy3@AvgQ)-n;1)VPBQ|7H;<?<Ia)5u6`Pb>18oUfl{4YV;P_TL;bIFrc0&=Gc!gKE>OF?<u2@t`Ir-b'
        '$KM{TTJF*+sGvP{BBYz>BjR0!P7g)CAHuk>UPwuG?^yI0=}=iP|I05mMt++Z|2}!YES%^f#^z;0h2h2p?S@4y40s`Fh@K>@n^RT('
        'pw@9hKlaBf3urY&V>o4bW1N4+SEIoOCuocp$B#{1#L-{tKuZ0M1poj'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
