# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/zhangge/worknote/ProtocolV4/uavcan/custom_data_types/dinosaurs/actuator/motion_controller/RobotMotionVelocity.1.0.uavcan
#
# Generated at:  2025-06-25 01:48:14.908069 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     dinosaurs.actuator.motion_controller.RobotMotionVelocity
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.time

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class RobotMotionVelocity_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 timestamp:             None | uavcan.time.SynchronizedTimestamp_1_0 = None,
                 longitudinal_velocity: None | int | float | _np_.float32 = None,
                 latteral_velocity:     None | int | float | _np_.float32 = None,
                 angular_velocity:      None | int | float | _np_.float32 = None) -> None:
        """
        dinosaurs.actuator.motion_controller.RobotMotionVelocity.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param timestamp:             uavcan.time.SynchronizedTimestamp.1.0 timestamp
        :param longitudinal_velocity: saturated float32 longitudinal_velocity
        :param latteral_velocity:     saturated float32 latteral_velocity
        :param angular_velocity:      saturated float32 angular_velocity
        """
        self._timestamp:             uavcan.time.SynchronizedTimestamp_1_0
        self._longitudinal_velocity: float
        self._latteral_velocity:     float
        self._angular_velocity:      float

        if timestamp is None:
            self.timestamp = uavcan.time.SynchronizedTimestamp_1_0()
        elif isinstance(timestamp, uavcan.time.SynchronizedTimestamp_1_0):
            self.timestamp = timestamp
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 '
                             f'got {type(timestamp).__name__}')

        self.longitudinal_velocity = longitudinal_velocity if longitudinal_velocity is not None else 0.0  # type: ignore

        self.latteral_velocity = latteral_velocity if latteral_velocity is not None else 0.0  # type: ignore

        self.angular_velocity = angular_velocity if angular_velocity is not None else 0.0  # type: ignore

    @property
    def timestamp(self) -> uavcan.time.SynchronizedTimestamp_1_0:
        """
        uavcan.time.SynchronizedTimestamp.1.0 timestamp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, x: uavcan.time.SynchronizedTimestamp_1_0) -> None:
        if isinstance(x, uavcan.time.SynchronizedTimestamp_1_0):
            self._timestamp = x
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 got {type(x).__name__}')

    @property
    def longitudinal_velocity(self) -> float:
        """
        saturated float32 longitudinal_velocity
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._longitudinal_velocity

    @longitudinal_velocity.setter
    def longitudinal_velocity(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._longitudinal_velocity = x
        else:
            raise ValueError(f'longitudinal_velocity: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    @property
    def latteral_velocity(self) -> float:
        """
        saturated float32 latteral_velocity
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._latteral_velocity

    @latteral_velocity.setter
    def latteral_velocity(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._latteral_velocity = x
        else:
            raise ValueError(f'latteral_velocity: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    @property
    def angular_velocity(self) -> float:
        """
        saturated float32 angular_velocity
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._angular_velocity

    @angular_velocity.setter
    def angular_velocity(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._angular_velocity = x
        else:
            raise ValueError(f'angular_velocity: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.timestamp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        if _np_.isfinite(self.longitudinal_velocity):
            if self.longitudinal_velocity > 340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(340282346638528859811704183484516925440.0)
            elif self.longitudinal_velocity < -340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_aligned_f32(self.longitudinal_velocity)
        else:
            _ser_.add_aligned_f32(self.longitudinal_velocity)
        if _np_.isfinite(self.latteral_velocity):
            if self.latteral_velocity > 340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(340282346638528859811704183484516925440.0)
            elif self.latteral_velocity < -340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_aligned_f32(self.latteral_velocity)
        else:
            _ser_.add_aligned_f32(self.latteral_velocity)
        if _np_.isfinite(self.angular_velocity):
            if self.angular_velocity > 340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(340282346638528859811704183484516925440.0)
            elif self.angular_velocity < -340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_aligned_f32(self.angular_velocity)
        else:
            _ser_.add_aligned_f32(self.angular_velocity)
        _ser_.pad_to_alignment(8)
        assert 152 <= (_ser_.current_bit_length - _base_offset_) <= 152, \
            'Bad serialization of dinosaurs.actuator.motion_controller.RobotMotionVelocity.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> RobotMotionVelocity_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "timestamp"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.time.SynchronizedTimestamp_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "longitudinal_velocity"
        _f1_ = _des_.fetch_aligned_f32()
        # Temporary _f2_ holds the value of "latteral_velocity"
        _f2_ = _des_.fetch_aligned_f32()
        # Temporary _f3_ holds the value of "angular_velocity"
        _f3_ = _des_.fetch_aligned_f32()
        self = RobotMotionVelocity_1_0(
            timestamp=_f0_,
            longitudinal_velocity=_f1_,
            latteral_velocity=_f2_,
            angular_velocity=_f3_)
        _des_.pad_to_alignment(8)
        assert 152 <= (_des_.consumed_bit_length - _base_offset_) <= 152, \
            'Bad deserialization of dinosaurs.actuator.motion_controller.RobotMotionVelocity.1.0'
        assert isinstance(self, RobotMotionVelocity_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'timestamp=%s' % self.timestamp,
            'longitudinal_velocity=%s' % self.longitudinal_velocity,
            'latteral_velocity=%s' % self.latteral_velocity,
            'angular_velocity=%s' % self.angular_velocity,
        ])
        return f'dinosaurs.actuator.motion_controller.RobotMotionVelocity.1.0({_o_0_})'

    _EXTENT_BYTES_ = 19

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8UR7IY0{^{MZEqb%6?RHezoad(+<?SOnWCz(rFe<$d)-?kJ_MJDa+@0~aYIx@SF^k0JJas&EHksVZ=g~u1T@k}jg&zY{zWDJ'
        '1^<L!(dX>mH@`#(kQyn;-kCG!Jaf)@o-?0b{_D+`7n(o*N7X2^Ssuk!7{zn-m?yc2;#3!vw#td%Uw+_Box0kHgHa{Iv#{}5_#~|R'
        'D{;vS?DsNNYRhY5BMvj}w22DslrG_=bVld7FwuRTXm__+ekgLCDmMy#DLxX$VkyW4zxZ(c{Ven^^%wpeJ`4V8%$+kTshzOlw+Q+i'
        'xKpd(uiQ~0&t@=J;*2{UJHjqsXcy%b|9Z`jQeH+*6(V{tDpP56sUC~$01MXfq6%_RE>Doimk?cE8y{bL9*)YWLOFE=9Bc2FRt-y$'
        'y<0jl6y|jDuEvRSaW2ZClcC=O%9L9d7divVANcR=PaM&)Xb*dLX^T?xr*J>`S7Tr-Gj6hZM^EYmSG!uM)MzV^{Ve#)ai-Jo=-)3a'
        'EF4I|%DPB|Vfv8GSy|>JcTDml!76U8$e2}SDwx%UVB8>t;bz1N{45<)CF~nZ7p;)f@j9GpqlVaCSCNQrHdd5imT)UJn6fMrhYC4i'
        'l`xyUs&bWbYKe%Eo3u8D{7jEfq}qxV6pAH+8S%RswZZX2ql=k$J1t-1j1>ST%uQy6XpB+~zqZ0fRXN0}Ia0V=14T8_S8xk}JK}jQ'
        '2&L1k6i1XM{BxM=;}+j^zq`AMl(1u!0jEegF#dF9g|SVx{b6_abY@}B6J0yDz1{1wk>JMOWXDpalC~;T&W$2=o9%WQpL1t{yGHLA'
        'cC70>Lm)(8tS(ED3TwGh`KX0}MqtX>DO#ir$AFe9(nVA!b#2M236Jfph6~0K4UWZ$LcU6eK4z&=R@tb%%wCROQ0eC0?EzaawPSbQ'
        '*<k2|61g;pmvV!qs4L3XTPzuYq!h8@qg?Z*#wZjtB5HsiOiINHf<J_@l|0X>!qjfVTx>SxZHPlLOH?7S(DtaC)&Wg%!%<sM4h-#<'
        'C=5dqZ4^L+SNzhRE{P^?$~(CxUmJhD-tWmD%QyN9#3y;9rOx8}gZ|*&uLnVH_%}ZgMxPDc^c(6%+4#8B$7K}!i*W-e_#aM0L7Y@*'
        'I1;l{lCX5Y=}(?d@W`%T#+6fAwb;Ki{>Hw)bSn@to79Q$YjZjnC!<z*=@#qqdvZr^))16TASmc0vhc*e5+AA)k;PP~SY=`0S7WPd'
        'lL~C)BCa^(!Y|T)xk`dx-iO+s?9=Kq$kU~tKscl(d0%{t#14l9|5zK`nM8JF-)N^(oj>g0{;iY-|NW{?!06bBVVx6@ne^Hq2mUf;'
        'FZkCkl-p=4x)o9Sf+K-jizT;!NrDiMDI1=kEdLs`5<spQxu*VsB4`7BptMsbgXSC*c7%Ad;fS4!*;KI!ir#VZ6zAYT=XI+JjVR3G'
        ';D=O03DzOcx`5<m<G|Fx7;lpFYNE>xE018K&8DqHst(m$=VN4iEYLgGno_powgmEa%1tvm&e-*f2bA#NZ3-DX9UHA(<I7eYnUcR;'
        'm+#77$-aC~-jxG+PY#;2UXGI-o%ZIWQ)j~iNp@#{2mjK~m3y!G{Xk4<<i8c`DtPuhCw5dM8jXM|-W7!&%kn+w0X+_8L-55ol@OpH'
        'h5z<G&q$rm8Oe`mcTnd!2GH4E+5IA{_j^xmf~Q2)dI<fcI>9{)RnlO^2S1^YMH;SXOC0Mj(XoZ67GoDw1;L4PgE}FyK?RoG><zHt'
        '7f4K|lOMx*`3~gGoto!R69zTemN!0!&w>vzSZW&OKl3+sI=8la+dG}z-JM={yVvW!-P_uF>sDv0x6|o$x?8(%Z+APLmhDaW>$xt6'
        'bY4L!@Io5DmgI)~!zm=6o{KI2_&)_)1z9mLzL{Xxpe87TIU7sJ+vNZEa#j9Cej>k+pUc0=r?uRBBHtOvUz}-Zzna$8>0(}C{POfA'
        '3bC5JMT1{G_Zo!;UGN@l6llymB8xmAy}544lC?hA4D>@H>VFY&?V=a3kiR+0)W6GrG{HZVyzTK!4yRPer(eT4dR)hxBjGPE<e6V?'
        'X$B=FarqD4zG{R1^Z&P$()BN)<TVEE5&j;-_%TQ(t2yp6a93C|dIY0KGo#7bGs_pBJ%Q25`Lk!1FFyMvjJ}*dyHuZFCSi!a2A*5`'
        ';5Q8b00'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
